package com.lswd.youpin.model;

import java.io.Serializable;
import java.util.Date;

public class AssociatorCard implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_card.cardid
     *
     * @mbg.generated
     */
    private Integer cardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_card.carduid
     *
     * @mbg.generated
     */
    private String carduid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_card.servicetime
     *
     * @mbg.generated
     */
    private Date servicetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_card.accountbalance
     *
     * @mbg.generated
     */
    private Float accountbalance = 0f;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_card.valid
     *
     * @mbg.generated
     */
    private Boolean valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_card.isdeleted
     *
     * @mbg.generated
     */
    private Boolean isdeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_card.isupload
     *
     * @mbg.generated
     */
    private Boolean isupload;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_card.cardType
     *
     * @mbg.generated
     */
    private Integer cardtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_card.cardid
     *
     * @return the value of dh_card.cardid
     *
     * @mbg.generated
     */
    public Integer getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_card.cardid
     *
     * @param cardid the value for dh_card.cardid
     *
     * @mbg.generated
     */
    public void setCardid(Integer cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_card.carduid
     *
     * @return the value of dh_card.carduid
     *
     * @mbg.generated
     */
    public String getCarduid() {
        return carduid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_card.carduid
     *
     * @param carduid the value for dh_card.carduid
     *
     * @mbg.generated
     */
    public void setCarduid(String carduid) {
        this.carduid = carduid == null ? null : carduid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_card.servicetime
     *
     * @return the value of dh_card.servicetime
     *
     * @mbg.generated
     */
    public Date getServicetime() {
        return servicetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_card.servicetime
     *
     * @param servicetime the value for dh_card.servicetime
     *
     * @mbg.generated
     */
    public void setServicetime(Date servicetime) {
        this.servicetime = servicetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_card.accountbalance
     *
     * @return the value of dh_card.accountbalance
     *
     * @mbg.generated
     */
    public Float getAccountbalance() {
        return accountbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_card.accountbalance
     *
     * @param accountbalance the value for dh_card.accountbalance
     *
     * @mbg.generated
     */
    public void setAccountbalance(Float accountbalance) {
        this.accountbalance = accountbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_card.valid
     *
     * @return the value of dh_card.valid
     *
     * @mbg.generated
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_card.valid
     *
     * @param valid the value for dh_card.valid
     *
     * @mbg.generated
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_card.isdeleted
     *
     * @return the value of dh_card.isdeleted
     *
     * @mbg.generated
     */
    public Boolean getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_card.isdeleted
     *
     * @param isdeleted the value for dh_card.isdeleted
     *
     * @mbg.generated
     */
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_card.isupload
     *
     * @return the value of dh_card.isupload
     *
     * @mbg.generated
     */
    public Boolean getIsupload() {
        return isupload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_card.isupload
     *
     * @param isupload the value for dh_card.isupload
     *
     * @mbg.generated
     */
    public void setIsupload(Boolean isupload) {
        this.isupload = isupload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_card.cardType
     *
     * @return the value of dh_card.cardType
     *
     * @mbg.generated
     */
    public Integer getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_card.cardType
     *
     * @param cardtype the value for dh_card.cardType
     *
     * @mbg.generated
     */
    public void setCardtype(Integer cardtype) {
        this.cardtype = cardtype;
    }
}