package com.lswd.youpin.model;

import java.util.Date;

public class AssociatorRefundBill {

    private String userName;
    private Associator associator;
    private String cardUid;
    private String refundTimeStr;
    private String refundTypeName;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Associator getAssociator() {
        return associator;
    }

    public void setAssociator(Associator associator) {
        this.associator = associator;
    }

    public String getCardUid() {
        return cardUid;
    }

    public void setCardUid(String cardUid) {
        this.cardUid = cardUid;
    }

    public String getRefundTimeStr() {
        return refundTimeStr;
    }

    public void setRefundTimeStr(String refundTimeStr) {
        this.refundTimeStr = refundTimeStr;
    }

    public String getRefundTypeName() {
        return refundTypeName;
    }

    public void setRefundTypeName(String refundTypeName) {
        this.refundTypeName = refundTypeName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_associator_refundbill.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_associator_refundbill.money
     *
     * @mbg.generated
     */
    private Float money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_associator_refundbill.associator_id
     *
     * @mbg.generated
     */
    private String associatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_associator_refundbill.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_associator_refundbill.refund_time
     *
     * @mbg.generated
     */
    private Date refundTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_associator_refundbill.refund_type
     *
     * @mbg.generated
     */
    private Integer refundType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_associator_refundbill.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_associator_refundbill.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_associator_refundbill.id
     *
     * @return the value of dh_associator_refundbill.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_associator_refundbill.id
     *
     * @param id the value for dh_associator_refundbill.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_associator_refundbill.money
     *
     * @return the value of dh_associator_refundbill.money
     *
     * @mbg.generated
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_associator_refundbill.money
     *
     * @param money the value for dh_associator_refundbill.money
     *
     * @mbg.generated
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_associator_refundbill.associator_id
     *
     * @return the value of dh_associator_refundbill.associator_id
     *
     * @mbg.generated
     */
    public String getAssociatorId() {
        return associatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_associator_refundbill.associator_id
     *
     * @param associatorId the value for dh_associator_refundbill.associator_id
     *
     * @mbg.generated
     */
    public void setAssociatorId(String associatorId) {
        this.associatorId = associatorId == null ? null : associatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_associator_refundbill.user_id
     *
     * @return the value of dh_associator_refundbill.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_associator_refundbill.user_id
     *
     * @param userId the value for dh_associator_refundbill.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_associator_refundbill.refund_time
     *
     * @return the value of dh_associator_refundbill.refund_time
     *
     * @mbg.generated
     */
    public Date getRefundTime() {
        return refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_associator_refundbill.refund_time
     *
     * @param refundTime the value for dh_associator_refundbill.refund_time
     *
     * @mbg.generated
     */
    public void setRefundTime(Date refundTime) {
        this.refundTime = refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_associator_refundbill.refund_type
     *
     * @return the value of dh_associator_refundbill.refund_type
     *
     * @mbg.generated
     */
    public Integer getRefundType() {
        return refundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_associator_refundbill.refund_type
     *
     * @param refundType the value for dh_associator_refundbill.refund_type
     *
     * @mbg.generated
     */
    public void setRefundType(Integer refundType) {
        this.refundType = refundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_associator_refundbill.safetyone
     *
     * @return the value of dh_associator_refundbill.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_associator_refundbill.safetyone
     *
     * @param safetyone the value for dh_associator_refundbill.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_associator_refundbill.safetytwo
     *
     * @return the value of dh_associator_refundbill.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_associator_refundbill.safetytwo
     *
     * @param safetytwo the value for dh_associator_refundbill.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }
}