package com.lswd.youpin.model;

public class AssociatorAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_associator_account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_associator_account.balance
     *
     * @mbg.generated
     */
    private Double balance=0.00;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_associator_account.credit
     *
     * @mbg.generated
     */
    private Double credit=0.00;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_associator_account.associator_id
     *
     * @mbg.generated
     */
    private String associatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_associator_account.account_type
     *
     * @mbg.generated
     */
    private Short accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_associator_account.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_associator_account.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_associator_account.id
     *
     * @return the value of t_associator_account.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_associator_account.id
     *
     * @param id the value for t_associator_account.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_associator_account.balance
     *
     * @return the value of t_associator_account.balance
     * @mbg.generated
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_associator_account.balance
     *
     * @param balance the value for t_associator_account.balance
     * @mbg.generated
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_associator_account.credit
     *
     * @return the value of t_associator_account.credit
     * @mbg.generated
     */
    public Double getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_associator_account.credit
     *
     * @param credit the value for t_associator_account.credit
     * @mbg.generated
     */
    public void setCredit(Double credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_associator_account.associator_id
     *
     * @return the value of t_associator_account.associator_id
     * @mbg.generated
     */
    public String getAssociatorId() {
        return associatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_associator_account.associator_id
     *
     * @param associatorId the value for t_associator_account.associator_id
     * @mbg.generated
     */
    public void setAssociatorId(String associatorId) {
        this.associatorId = associatorId == null ? null : associatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_associator_account.account_type
     *
     * @return the value of t_associator_account.account_type
     * @mbg.generated
     */
    public Short getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_associator_account.account_type
     *
     * @param accountType the value for t_associator_account.account_type
     * @mbg.generated
     */
    public void setAccountType(Short accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_associator_account.safetyone
     *
     * @return the value of t_associator_account.safetyone
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_associator_account.safetyone
     *
     * @param safetyone the value for t_associator_account.safetyone
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_associator_account.safetytwo
     *
     * @return the value of t_associator_account.safetytwo
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_associator_account.safetytwo
     *
     * @param safetytwo the value for t_associator_account.safetytwo
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }
}