package com.lswd.youpin.model;

import com.lswd.youpin.model.lsyp.Supplier;

import java.util.Date;
import java.util.List;

public class Canteen {

    private String tenantName;

    public String getTenantName() {
        return tenantName;
    }

    public void setTenantName(String tenantName) {
        this.tenantName = tenantName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.canteen_id
     *
     * @mbg.generated
     */
    private String canteenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.canteen_name
     *
     * @mbg.generated
     */
    private String canteenName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.leader
     *
     * @mbg.generated
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.institution_id
     *
     * @mbg.generated
     */
    private String institutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.tenant_id
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.canteen_type
     *
     * @mbg.generated
     */
    private Short canteenType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.level
     *
     * @mbg.generated
     */
    private Short level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.pay_type
     *
     * @mbg.generated
     */
    private Boolean isCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.is_use
     *
     * @mbg.generated
     */
    private Boolean isUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    private String pickingTime;

    private String deadline;

    private Boolean isAssess;

    private Boolean isWarning;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    private String institutionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    private List<Supplier> suppliers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.safetytwo
     *
     * @mbg.generated
     */
    private String regionId;


    private Double distance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen.safetythree
     *
     * @mbg.generated
     */
    private String imageUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.id
     *
     * @return the value of t_canteen.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.id
     *
     * @param id the value for t_canteen.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.canteen_id
     *
     * @return the value of t_canteen.canteen_id
     *
     * @mbg.generated
     */
    public String getCanteenId() {
        return canteenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.canteen_id
     *
     * @param canteenId the value for t_canteen.canteen_id
     *
     * @mbg.generated
     */
    public void setCanteenId(String canteenId) {
        this.canteenId = canteenId == null ? null : canteenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.canteen_name
     *
     * @return the value of t_canteen.canteen_name
     *
     * @mbg.generated
     */
    public String getCanteenName() {
        return canteenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.canteen_name
     *
     * @param canteenName the value for t_canteen.canteen_name
     *
     * @mbg.generated
     */
    public void setCanteenName(String canteenName) {
        this.canteenName = canteenName == null ? null : canteenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.leader
     *
     * @return the value of t_canteen.leader
     *
     * @mbg.generated
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.leader
     *
     * @param leader the value for t_canteen.leader
     *
     * @mbg.generated
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.telephone
     *
     * @return the value of t_canteen.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.telephone
     *
     * @param telephone the value for t_canteen.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.institution_id
     *
     * @return the value of t_canteen.institution_id
     *
     * @mbg.generated
     */
    public String getInstitutionId() {
        return institutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.institution_id
     *
     * @param institutionId the value for t_canteen.institution_id
     *
     * @mbg.generated
     */
    public void setInstitutionId(String institutionId) {
        this.institutionId = institutionId == null ? null : institutionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.canteen_type
     *
     * @return the value of t_canteen.canteen_type
     *
     * @mbg.generated
     */
    public Short getCanteenType() {
        return canteenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.canteen_type
     *
     * @param canteenType the value for t_canteen.canteen_type
     *
     * @mbg.generated
     */
    public void setCanteenType(Short canteenType) {
        this.canteenType = canteenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.level
     *
     * @return the value of t_canteen.level
     *
     * @mbg.generated
     */
    public Short getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.level
     *
     * @param level the value for t_canteen.level
     *
     * @mbg.generated
     */
    public void setLevel(Short level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.is_use
     *
     * @return the value of t_canteen.is_use
     *
     * @mbg.generated
     */
    public Boolean getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.is_use
     *
     * @param isUse the value for t_canteen.is_use
     *
     * @mbg.generated
     */
    public void setIsUse(Boolean isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.is_delete
     *
     * @return the value of t_canteen.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.is_delete
     *
     * @param isDelete the value for t_canteen.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.address
     *
     * @return the value of t_canteen.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.address
     *
     * @param address the value for t_canteen.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.longitude
     *
     * @return the value of t_canteen.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.longitude
     *
     * @param longitude the value for t_canteen.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.latitude
     *
     * @return the value of t_canteen.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.latitude
     *
     * @param latitude the value for t_canteen.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.description
     *
     * @return the value of t_canteen.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.description
     *
     * @param description the value for t_canteen.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.create_user
     *
     * @return the value of t_canteen.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.create_user
     *
     * @param createUser the value for t_canteen.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.update_user
     *
     * @return the value of t_canteen.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.update_user
     *
     * @param updateUser the value for t_canteen.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.create_time
     *
     * @return the value of t_canteen.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.create_time
     *
     * @param createTime the value for t_canteen.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen.update_time
     *
     * @return the value of t_canteen.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen.update_time
     *
     * @param updateTime the value for t_canteen.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public List<Supplier> getSuppliers() {
        return suppliers;
    }

    public void setSuppliers(List<Supplier> suppliers) {
        this.suppliers = suppliers;
    }

    public String getTenantId() {
        return tenantId;
    }

    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    public String getRegionId() {
        return regionId;
    }

    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public Double getDistance() {
        return distance;
    }

    public void setDistance(Double distance) {
        this.distance = distance;
    }

    public Boolean getAssess() {
        return isAssess;
    }

    public void setAssess(Boolean assess) {
        isAssess = assess;
    }

    public String getPickingTime() {
        return pickingTime;
    }

    public void setPickingTime(String pickingTime) {
        this.pickingTime = pickingTime;
    }

    public Boolean getCard() {
        return isCard;
    }

    public void setCard(Boolean card) {
        isCard = card;
    }

    public String getInstitutionName() {
        return institutionName;
    }

    public void setInstitutionName(String institutionName) {
        this.institutionName = institutionName;
    }

    public String getDeadline() {
        return deadline;
    }

    public void setDeadline(String deadline) {
        this.deadline = deadline;
    }

    public Boolean getWarning() {
        return isWarning;
    }

    public void setWarning(Boolean warning) {
        isWarning = warning;
    }

    private Double outFee;
    public Double getOutFee() {
        return outFee;
    }

    public void setOutFee(Double outFee) {
        this.outFee = outFee;
    }
}