package com.lswd.youpin.model;

import java.util.Date;

public class RechargeLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge_log.out_trade_no
     *
     * @mbg.generated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge_log.associator_id
     *
     * @mbg.generated
     */
    private String associatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge_log.recharge_money
     *
     * @mbg.generated
     */
    private Float rechargeMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge_log.recharge_type
     *
     * @mbg.generated
     */
    private Short rechargeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge_log.operation_time
     *
     * @mbg.generated
     */
    private Date operationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge_log.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge_log.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge_log.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge_log.id
     *
     * @return the value of t_recharge_log.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge_log.id
     *
     * @param id the value for t_recharge_log.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge_log.out_trade_no
     *
     * @return the value of t_recharge_log.out_trade_no
     * @mbg.generated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge_log.out_trade_no
     *
     * @param outTradeNo the value for t_recharge_log.out_trade_no
     * @mbg.generated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge_log.associator_id
     *
     * @return the value of t_recharge_log.associator_id
     * @mbg.generated
     */
    public String getAssociatorId() {
        return associatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge_log.associator_id
     *
     * @param associatorId the value for t_recharge_log.associator_id
     * @mbg.generated
     */
    public void setAssociatorId(String associatorId) {
        this.associatorId = associatorId == null ? null : associatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge_log.recharge_money
     *
     * @return the value of t_recharge_log.recharge_money
     * @mbg.generated
     */
    public Float getRechargeMoney() {
        return rechargeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge_log.recharge_money
     *
     * @param rechargeMoney the value for t_recharge_log.recharge_money
     * @mbg.generated
     */
    public void setRechargeMoney(Float rechargeMoney) {
        this.rechargeMoney = rechargeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge_log.recharge_type
     *
     * @return the value of t_recharge_log.recharge_type
     * @mbg.generated
     */
    public Short getRechargeType() {
        return rechargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge_log.recharge_type
     *
     * @param rechargeType the value for t_recharge_log.recharge_type
     * @mbg.generated
     */
    public void setRechargeType(Short rechargeType) {
        this.rechargeType = rechargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge_log.operation_time
     *
     * @return the value of t_recharge_log.operation_time
     * @mbg.generated
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge_log.operation_time
     *
     * @param operationTime the value for t_recharge_log.operation_time
     * @mbg.generated
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge_log.remark
     *
     * @return the value of t_recharge_log.remark
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge_log.remark
     *
     * @param remark the value for t_recharge_log.remark
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge_log.safetyone
     *
     * @return the value of t_recharge_log.safetyone
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge_log.safetyone
     *
     * @param safetyone the value for t_recharge_log.safetyone
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge_log.safetytwo
     *
     * @return the value of t_recharge_log.safetytwo
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge_log.safetytwo
     *
     * @param safetytwo the value for t_recharge_log.safetytwo
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }

    private String rechargeName;

    public String getRechargeName() {return rechargeName;}

    public void setRechargeName(String rechargeName) {this.rechargeName = rechargeName==null?null:rechargeName.trim();}

    private String associatorName;

    public String getAssociatorName() {return associatorName;}

    public void setAssociatorName(String associatorName) {this.associatorName = associatorName==null?null:associatorName.trim();}
}