package com.lswd.youpin.model;

import java.util.List;

public class ShowImages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_images.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_images.img
     *
     * @mbg.generated
     */
    private String newImg;


    private List<String> oldImgs;

    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_images.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_images.canteen_id
     *
     * @mbg.generated
     */
    private String canteenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_images.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_images.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_images.id
     *
     * @return the value of t_images.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_images.id
     *
     * @param id the value for t_images.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_images.description
     *
     * @return the value of t_images.description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_images.description
     *
     * @param description the value for t_images.description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_images.canteen_id
     *
     * @return the value of t_images.canteen_id
     * @mbg.generated
     */
    public String getCanteenId() {
        return canteenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_images.canteen_id
     *
     * @param canteenId the value for t_images.canteen_id
     * @mbg.generated
     */
    public void setCanteenId(String canteenId) {
        this.canteenId = canteenId == null ? null : canteenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_images.safetyone
     *
     * @return the value of t_images.safetyone
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_images.safetyone
     *
     * @param safetyone the value for t_images.safetyone
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_images.safetytwo
     *
     * @return the value of t_images.safetytwo
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_images.safetytwo
     *
     * @param safetytwo the value for t_images.safetytwo
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }

    public String getNewImg() {
        return newImg;
    }

    public void setNewImg(String newImg) {
        this.newImg = newImg;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public List<String> getOldImgs() {
        return oldImgs;
    }

    public void setOldImgs(List<String> oldImgs) {
        this.oldImgs = oldImgs;
    }
}