package com.lswd.youpin.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class User implements Serializable {

    public User() {
    }

    public User(Integer id, String username, String password, Integer roleId, String canteenIds, String userId) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.roleId = roleId;
        this.canteenIds = canteenIds;
        this.userId = userId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbg.generated
     */

    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_type
     *
     * @mbg.generated
     */
    private Boolean userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.is_use
     *
     * @mbg.generated
     */
    private Boolean isUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.lock_time
     *
     * @mbg.generated
     */
    private Short lockTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;


    private Role role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.tenant_id
     *
     * @mbg.generated
     */
    private String tenantId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.safetythree
     *
     * @mbg.generated
     */
    private String safetythree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.safetyfour
     *
     * @mbg.generated
     */
    private String safetyfour;

    /**
     * 用来存储用户UUID
     */

    private String uuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     * @mbg.generated
     */

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.telephone
     *
     * @return the value of t_user.telephone
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.telephone
     *
     * @param telephone the value for t_user.telephone
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_type
     *
     * @return the value of t_user.user_type
     * @mbg.generated
     */
    public Boolean getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_type
     *
     * @param userType the value for t_user.user_type
     * @mbg.generated
     */
    public void setUserType(Boolean userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.is_delete
     *
     * @return the value of t_user.is_delete
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.is_delete
     *
     * @param isDelete the value for t_user.is_delete
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.is_use
     *
     * @return the value of t_user.is_use
     * @mbg.generated
     */
    public Boolean getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.is_use
     *
     * @param isUse the value for t_user.is_use
     * @mbg.generated
     */
    public void setIsUse(Boolean isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.lock_time
     *
     * @return the value of t_user.lock_time
     * @mbg.generated
     */
    public Short getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.lock_time
     *
     * @param lockTime the value for t_user.lock_time
     * @mbg.generated
     */
    public void setLockTime(Short lockTime) {
        this.lockTime = lockTime;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.tenant_id
     *
     * @return the value of t_user.tenant_id
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.tenant_id
     *
     * @param tenantId the value for t_user.tenant_id
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.create_time
     *
     * @return the value of t_user.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.create_time
     *
     * @param createTime the value for t_user.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.update_time
     *
     * @return the value of t_user.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.update_time
     *
     * @param updateTime the value for t_user.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.safetyone
     *
     * @return the value of t_user.safetyone
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.safetyone
     *
     * @param safetyone the value for t_user.safetyone
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.safetytwo
     *
     * @return the value of t_user.safetytwo
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.safetytwo
     *
     * @param safetytwo the value for t_user.safetytwo
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.safetythree
     *
     * @return the value of t_user.safetythree
     * @mbg.generated
     */
    public String getSafetythree() {
        return safetythree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.safetythree
     *
     * @param safetythree the value for t_user.safetythree
     * @mbg.generated
     */
    public void setSafetythree(String safetythree) {
        this.safetythree = safetythree == null ? null : safetythree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.safetyfour
     *
     * @return the value of t_user.safetyfour
     * @mbg.generated
     */
    public String getSafetyfour() {
        return safetyfour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.safetyfour
     *
     * @param safetyfour the value for t_user.safetyfour
     * @mbg.generated
     */
    public void setSafetyfour(String safetyfour) {
        this.safetyfour = safetyfour == null ? null : safetyfour.trim();
    }

    /**
     * 获取uuid值
     */
    public String getUUID() {
        return uuid;
    }

    /**
     * 设置uuid置
     */
    public void setUUID(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    private Integer status;

    private String state;

    public Integer getStatus() {return status;}

    public String getState() {return state;}

    public void setStatus(Integer status) {this.status = status;}

    public void setState(String state) {this.state = state;}

    private String nickname;

    public String getNickname() {return nickname;}

    public void setNickname(String nickname) {this.nickname = nickname;}

    private String connectperson;

    public String getConnectperson() {return connectperson;}

    public void setConnectperson(String connectperson) {this.connectperson = connectperson;}

    private String remark;

    public String getRemark() {return remark;}

    public void setRemark(String remark) {this.remark = remark;}

    private String canteenIds;

    public String getCanteenIds() {return canteenIds;}

    public void setCanteenIds(String canteenIds) {this.canteenIds = canteenIds;}

    private List<Canteen>restaurants;

    public List<Canteen> getRestaurants() {return restaurants;}

    public void setRestaurants(List<Canteen> restaurants) {this.restaurants = restaurants;}

    private String userId;

    public String getUserId() {return userId;}

    public void setUserId(String userId) {this.userId = userId;}

    private Date lockDate;

    public void setLockDate(Date lockDate) {this.lockDate = lockDate;}

    public Date getLockDate() {return lockDate;}
}