package com.lswd.youpin.dao.lsygen;

import com.lswd.youpin.model.lsy.AppResource;

public interface AppResourceMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_app_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_app_resource
     *
     * @mbg.generated
     */
    int insert(AppResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_app_resource
     *
     * @mbg.generated
     */
    int insertSelective(AppResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_app_resource
     *
     * @mbg.generated
     */
    AppResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_app_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_app_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppResource record);
}