package com.lswd.youpin.dao.lsygen;

import com.lswd.youpin.model.lsy.Pdf;

public interface PdfMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_pdf
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_pdf
     *
     * @mbg.generated
     */
    int insert(Pdf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_pdf
     *
     * @mbg.generated
     */
    int insertSelective(Pdf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_pdf
     *
     * @mbg.generated
     */
    Pdf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_pdf
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Pdf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_pdf
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Pdf record);
}