package com.lswd.youpin.dao.lsygen;

import com.lswd.youpin.model.lsy.Position;

public interface PositionMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_position
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_position
     *
     * @mbg.generated
     */
    int insert(Position record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_position
     *
     * @mbg.generated
     */
    int insertSelective(Position record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_position
     *
     * @mbg.generated
     */
    Position selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_position
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Position record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_position
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Position record);
}