package com.lswd.youpin.dao.lsygen;

import com.lswd.youpin.model.lsy.UploadLog;

public interface UploadLogMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_upload_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_upload_log
     *
     * @mbg.generated
     */
    int insert(UploadLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_upload_log
     *
     * @mbg.generated
     */
    int insertSelective(UploadLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_upload_log
     *
     * @mbg.generated
     */
    UploadLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_upload_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UploadLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_upload_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UploadLog record);
}