package com.lswd.youpin.model.lsyp;

public class CanteenSupplier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen_supplier.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen_supplier.canteen_id
     *
     * @mbg.generated
     */
    private String canteenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen_supplier.supplier_id
     *
     * @mbg.generated
     */
    private String supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen_supplier.satetyone
     *
     * @mbg.generated
     */
    private String satetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_canteen_supplier.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen_supplier.id
     *
     * @return the value of t_canteen_supplier.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen_supplier.id
     *
     * @param id the value for t_canteen_supplier.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen_supplier.canteen_id
     *
     * @return the value of t_canteen_supplier.canteen_id
     *
     * @mbg.generated
     */
    public String getCanteenId() {
        return canteenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen_supplier.canteen_id
     *
     * @param canteenId the value for t_canteen_supplier.canteen_id
     *
     * @mbg.generated
     */
    public void setCanteenId(String canteenId) {
        this.canteenId = canteenId == null ? null : canteenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen_supplier.supplier_id
     *
     * @return the value of t_canteen_supplier.supplier_id
     *
     * @mbg.generated
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen_supplier.supplier_id
     *
     * @param supplierId the value for t_canteen_supplier.supplier_id
     *
     * @mbg.generated
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId == null ? null : supplierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen_supplier.satetyone
     *
     * @return the value of t_canteen_supplier.satetyone
     *
     * @mbg.generated
     */
    public String getSatetyone() {
        return satetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen_supplier.satetyone
     *
     * @param satetyone the value for t_canteen_supplier.satetyone
     *
     * @mbg.generated
     */
    public void setSatetyone(String satetyone) {
        this.satetyone = satetyone == null ? null : satetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_canteen_supplier.safetytwo
     *
     * @return the value of t_canteen_supplier.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_canteen_supplier.safetytwo
     *
     * @param safetytwo the value for t_canteen_supplier.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }
}