package com.lswd.youpin.model.lsyp;

public class CounterOrderItems {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order_items.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order_items.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order_items.menu_id
     *
     * @mbg.generated
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order_items.menu_name
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order_items.menu_vip_price
     *
     * @mbg.generated
     */
    private Float menuVipPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order_items.menu_market_price
     *
     * @mbg.generated
     */
    private Float menuMarketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order_items.menu_type_name
     *
     * @mbg.generated
     */
    private String menuTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order_items.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order_items.order_amount
     *
     * @mbg.generated
     */
    private Float orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order_items.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order_items.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order_items.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order_items.id
     *
     * @return the value of dh_counter_order_items.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order_items.id
     *
     * @param id the value for dh_counter_order_items.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order_items.order_id
     *
     * @return the value of dh_counter_order_items.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order_items.order_id
     *
     * @param orderId the value for dh_counter_order_items.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order_items.menu_id
     *
     * @return the value of dh_counter_order_items.menu_id
     *
     * @mbg.generated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order_items.menu_id
     *
     * @param menuId the value for dh_counter_order_items.menu_id
     *
     * @mbg.generated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order_items.menu_name
     *
     * @return the value of dh_counter_order_items.menu_name
     *
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order_items.menu_name
     *
     * @param menuName the value for dh_counter_order_items.menu_name
     *
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order_items.menu_vip_price
     *
     * @return the value of dh_counter_order_items.menu_vip_price
     *
     * @mbg.generated
     */
    public Float getMenuVipPrice() {
        return menuVipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order_items.menu_vip_price
     *
     * @param menuVipPrice the value for dh_counter_order_items.menu_vip_price
     *
     * @mbg.generated
     */
    public void setMenuVipPrice(Float menuVipPrice) {
        this.menuVipPrice = menuVipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order_items.menu_market_price
     *
     * @return the value of dh_counter_order_items.menu_market_price
     *
     * @mbg.generated
     */
    public Float getMenuMarketPrice() {
        return menuMarketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order_items.menu_market_price
     *
     * @param menuMarketPrice the value for dh_counter_order_items.menu_market_price
     *
     * @mbg.generated
     */
    public void setMenuMarketPrice(Float menuMarketPrice) {
        this.menuMarketPrice = menuMarketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order_items.menu_type_name
     *
     * @return the value of dh_counter_order_items.menu_type_name
     *
     * @mbg.generated
     */
    public String getMenuTypeName() {
        return menuTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order_items.menu_type_name
     *
     * @param menuTypeName the value for dh_counter_order_items.menu_type_name
     *
     * @mbg.generated
     */
    public void setMenuTypeName(String menuTypeName) {
        this.menuTypeName = menuTypeName == null ? null : menuTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order_items.quantity
     *
     * @return the value of dh_counter_order_items.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order_items.quantity
     *
     * @param quantity the value for dh_counter_order_items.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order_items.order_amount
     *
     * @return the value of dh_counter_order_items.order_amount
     *
     * @mbg.generated
     */
    public Float getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order_items.order_amount
     *
     * @param orderAmount the value for dh_counter_order_items.order_amount
     *
     * @mbg.generated
     */
    public void setOrderAmount(Float orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order_items.description
     *
     * @return the value of dh_counter_order_items.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order_items.description
     *
     * @param description the value for dh_counter_order_items.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order_items.safetyone
     *
     * @return the value of dh_counter_order_items.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order_items.safetyone
     *
     * @param safetyone the value for dh_counter_order_items.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order_items.safetytwo
     *
     * @return the value of dh_counter_order_items.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order_items.safetytwo
     *
     * @param safetytwo the value for dh_counter_order_items.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }
}