package com.lswd.youpin.model.lsyp;

import java.util.Date;

public class CounterMenu {
    private Integer number = 0;

    private Float menuTotal = 0F;

    public Float getMenuTotal() {
        return menuTotal;
    }

    public void setMenuTotal(Float menuTotal) {
        this.menuTotal = menuTotal;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    private Date bingTime;

    private String bingUser;

    public String getBingUser() {
        return bingUser;
    }

    public void setBingUser(String bingUser) {
        this.bingUser = bingUser;
    }

    public Date getBingTime() {
        return bingTime;
    }

    public void setBingTime(Date bingTime) {
        this.bingTime = bingTime;
    }

    private Counter counter;

    public Counter getCounter() {
        return counter;
    }

    public void setCounter(Counter counter) {
        this.counter = counter;
    }

    private boolean checked;

    public boolean isChecked() {
        return checked;
    }

    public void setChecked(boolean checked) {
        this.checked = checked;
    }

    private String menuTypeName;

    public String getMenuTypeName() {
        return menuTypeName;
    }

    public void setMenuTypeName(String menuTypeName) {
        this.menuTypeName = menuTypeName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.menu_id
     *
     * @mbg.generated
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.menu_name
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.counter_id
     *
     * @mbg.generated
     */
    private String counterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.imageurl
     *
     * @mbg.generated
     */
    private String imageurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.surplus
     *
     * @mbg.generated
     */
    private Integer surplus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.vip_price
     *
     * @mbg.generated
     */
    private Float vipPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.market_price
     *
     * @mbg.generated
     */
    private Float marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.unit_id
     *
     * @mbg.generated
     */
    private Integer unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.menutype_id
     *
     * @mbg.generated
     */
    private Integer menutypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.id
     *
     * @return the value of dh_counter_menu.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.id
     *
     * @param id the value for dh_counter_menu.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.menu_id
     *
     * @return the value of dh_counter_menu.menu_id
     *
     * @mbg.generated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.menu_id
     *
     * @param menuId the value for dh_counter_menu.menu_id
     *
     * @mbg.generated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.menu_name
     *
     * @return the value of dh_counter_menu.menu_name
     *
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.menu_name
     *
     * @param menuName the value for dh_counter_menu.menu_name
     *
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.counter_id
     *
     * @return the value of dh_counter_menu.counter_id
     *
     * @mbg.generated
     */
    public String getCounterId() {
        return counterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.counter_id
     *
     * @param counterId the value for dh_counter_menu.counter_id
     *
     * @mbg.generated
     */
    public void setCounterId(String counterId) {
        this.counterId = counterId == null ? null : counterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.imageurl
     *
     * @return the value of dh_counter_menu.imageurl
     *
     * @mbg.generated
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.imageurl
     *
     * @param imageurl the value for dh_counter_menu.imageurl
     *
     * @mbg.generated
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.surplus
     *
     * @return the value of dh_counter_menu.surplus
     *
     * @mbg.generated
     */
    public Integer getSurplus() {
        return surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.surplus
     *
     * @param surplus the value for dh_counter_menu.surplus
     *
     * @mbg.generated
     */
    public void setSurplus(Integer surplus) {
        this.surplus = surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.vip_price
     *
     * @return the value of dh_counter_menu.vip_price
     *
     * @mbg.generated
     */
    public Float getVipPrice() {
        return vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.vip_price
     *
     * @param vipPrice the value for dh_counter_menu.vip_price
     *
     * @mbg.generated
     */
    public void setVipPrice(Float vipPrice) {
        this.vipPrice = vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.market_price
     *
     * @return the value of dh_counter_menu.market_price
     *
     * @mbg.generated
     */
    public Float getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.market_price
     *
     * @param marketPrice the value for dh_counter_menu.market_price
     *
     * @mbg.generated
     */
    public void setMarketPrice(Float marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.unit_id
     *
     * @return the value of dh_counter_menu.unit_id
     *
     * @mbg.generated
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.unit_id
     *
     * @param unitId the value for dh_counter_menu.unit_id
     *
     * @mbg.generated
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.menutype_id
     *
     * @return the value of dh_counter_menu.menutype_id
     *
     * @mbg.generated
     */
    public Integer getMenutypeId() {
        return menutypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.menutype_id
     *
     * @param menutypeId the value for dh_counter_menu.menutype_id
     *
     * @mbg.generated
     */
    public void setMenutypeId(Integer menutypeId) {
        this.menutypeId = menutypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.is_delete
     *
     * @return the value of dh_counter_menu.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.is_delete
     *
     * @param isDelete the value for dh_counter_menu.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.create_user
     *
     * @return the value of dh_counter_menu.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.create_user
     *
     * @param createUser the value for dh_counter_menu.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.update_user
     *
     * @return the value of dh_counter_menu.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.update_user
     *
     * @param updateUser the value for dh_counter_menu.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.create_time
     *
     * @return the value of dh_counter_menu.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.create_time
     *
     * @param createTime the value for dh_counter_menu.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.update_time
     *
     * @return the value of dh_counter_menu.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.update_time
     *
     * @param updateTime the value for dh_counter_menu.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.safetyone
     *
     * @return the value of dh_counter_menu.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.safetyone
     *
     * @param safetyone the value for dh_counter_menu.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu.safetytwo
     *
     * @return the value of dh_counter_menu.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu.safetytwo
     *
     * @param safetytwo the value for dh_counter_menu.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }
}