package com.lswd.youpin.model.lsyp;

import java.util.Date;

public class Counter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter.counter_id
     *
     * @mbg.generated
     */
    private String counterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter.counter_name
     *
     * @mbg.generated
     */
    private String counterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter.canteen_id
     *
     * @mbg.generated
     */
    private String canteenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter.imageurl
     *
     * @mbg.generated
     */
    private String imageurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter.is_delete
     *
     * @mbg.generated
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter.id
     *
     * @return the value of dh_counter.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter.id
     *
     * @param id the value for dh_counter.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter.counter_id
     *
     * @return the value of dh_counter.counter_id
     *
     * @mbg.generated
     */
    public String getCounterId() {
        return counterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter.counter_id
     *
     * @param counterId the value for dh_counter.counter_id
     *
     * @mbg.generated
     */
    public void setCounterId(String counterId) {
        this.counterId = counterId == null ? null : counterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter.counter_name
     *
     * @return the value of dh_counter.counter_name
     *
     * @mbg.generated
     */
    public String getCounterName() {
        return counterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter.counter_name
     *
     * @param counterName the value for dh_counter.counter_name
     *
     * @mbg.generated
     */
    public void setCounterName(String counterName) {
        this.counterName = counterName == null ? null : counterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter.canteen_id
     *
     * @return the value of dh_counter.canteen_id
     *
     * @mbg.generated
     */
    public String getcanteenId() {
        return canteenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter.canteen_id
     *
     * @param canteenId the value for dh_counter.canteen_id
     *
     * @mbg.generated
     */
    public void setcanteenId(String canteenId) {
        this.canteenId = canteenId == null ? null : canteenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter.address
     *
     * @return the value of dh_counter.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter.address
     *
     * @param address the value for dh_counter.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter.imageurl
     *
     * @return the value of dh_counter.imageurl
     *
     * @mbg.generated
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter.imageurl
     *
     * @param imageurl the value for dh_counter.imageurl
     *
     * @mbg.generated
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter.description
     *
     * @return the value of dh_counter.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter.description
     *
     * @param description the value for dh_counter.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter.is_delete
     *
     * @return the value of dh_counter.is_delete
     *
     * @mbg.generated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter.is_delete
     *
     * @param isDelete the value for dh_counter.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter.create_time
     *
     * @return the value of dh_counter.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter.create_time
     *
     * @param createTime the value for dh_counter.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter.create_user
     *
     * @return the value of dh_counter.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter.create_user
     *
     * @param createUser the value for dh_counter.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter.update_user
     *
     * @return the value of dh_counter.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter.update_user
     *
     * @param updateUser the value for dh_counter.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter.update_time
     *
     * @return the value of dh_counter.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter.update_time
     *
     * @param updateTime the value for dh_counter.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter.safetyone
     *
     * @return the value of dh_counter.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter.safetyone
     *
     * @param safetyone the value for dh_counter.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter.safetytwo
     *
     * @return the value of dh_counter.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter.safetytwo
     *
     * @param safetytwo the value for dh_counter.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }
}