package com.lswd.youpin.model.lsyp;

import java.util.Date;

public class CounterMenuLinked {

    private boolean checked;

    public boolean isChecked() {
        return checked;
    }

    public void setChecked(boolean checked) {
        this.checked = checked;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu_linked.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu_linked.counter_id
     *
     * @mbg.generated
     */
    private String counterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu_linked.menutype_id
     *
     * @mbg.generated
     */
    private Integer menutypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu_linked.menu_id
     *
     * @mbg.generated
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu_linked.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu_linked.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu_linked.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu_linked.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu_linked.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_menu_linked.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu_linked.id
     *
     * @return the value of dh_counter_menu_linked.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu_linked.id
     *
     * @param id the value for dh_counter_menu_linked.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu_linked.counter_id
     *
     * @return the value of dh_counter_menu_linked.counter_id
     *
     * @mbg.generated
     */
    public String getCounterId() {
        return counterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu_linked.counter_id
     *
     * @param counterId the value for dh_counter_menu_linked.counter_id
     *
     * @mbg.generated
     */
    public void setCounterId(String counterId) {
        this.counterId = counterId == null ? null : counterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu_linked.menutype_id
     *
     * @return the value of dh_counter_menu_linked.menutype_id
     *
     * @mbg.generated
     */
    public Integer getMenutypeId() {
        return menutypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu_linked.menutype_id
     *
     * @param menutypeId the value for dh_counter_menu_linked.menutype_id
     *
     * @mbg.generated
     */
    public void setMenutypeId(Integer menutypeId) {
        this.menutypeId = menutypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu_linked.menu_id
     *
     * @return the value of dh_counter_menu_linked.menu_id
     *
     * @mbg.generated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu_linked.menu_id
     *
     * @param menuId the value for dh_counter_menu_linked.menu_id
     *
     * @mbg.generated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu_linked.create_time
     *
     * @return the value of dh_counter_menu_linked.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu_linked.create_time
     *
     * @param createTime the value for dh_counter_menu_linked.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu_linked.create_user
     *
     * @return the value of dh_counter_menu_linked.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu_linked.create_user
     *
     * @param createUser the value for dh_counter_menu_linked.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu_linked.update_user
     *
     * @return the value of dh_counter_menu_linked.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu_linked.update_user
     *
     * @param updateUser the value for dh_counter_menu_linked.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu_linked.update_time
     *
     * @return the value of dh_counter_menu_linked.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu_linked.update_time
     *
     * @param updateTime the value for dh_counter_menu_linked.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu_linked.safetyone
     *
     * @return the value of dh_counter_menu_linked.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu_linked.safetyone
     *
     * @param safetyone the value for dh_counter_menu_linked.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_menu_linked.safetytwo
     *
     * @return the value of dh_counter_menu_linked.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_menu_linked.safetytwo
     *
     * @param safetytwo the value for dh_counter_menu_linked.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }
}