package com.lswd.youpin.model.lsyp;

import java.util.Date;

public class CounterTypeRecipeCategory {

    private String counterTypeName;
    private String recipeCategoryName;

    public String getCounterTypeName() {
        return counterTypeName;
    }

    public void setCounterTypeName(String counterTypeName) {
        this.counterTypeName = counterTypeName;
    }

    public String getRecipeCategoryName() {
        return recipeCategoryName;
    }

    public void setRecipeCategoryName(String recipeCategoryName) {
        this.recipeCategoryName = recipeCategoryName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_type_recipe_category.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_type_recipe_category.counter_type_id
     *
     * @mbg.generated
     */
    private Integer counterTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_type_recipe_category.recipe_category_id
     *
     * @mbg.generated
     */
    private Integer recipeCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_type_recipe_category.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_type_recipe_category.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_type_recipe_category.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_type_recipe_category.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_type_recipe_category.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_type_recipe_category.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_type_recipe_category.id
     *
     * @return the value of dh_counter_type_recipe_category.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_type_recipe_category.id
     *
     * @param id the value for dh_counter_type_recipe_category.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_type_recipe_category.counter_type_id
     *
     * @return the value of dh_counter_type_recipe_category.counter_type_id
     *
     * @mbg.generated
     */
    public Integer getCounterTypeId() {
        return counterTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_type_recipe_category.counter_type_id
     *
     * @param counterTypeId the value for dh_counter_type_recipe_category.counter_type_id
     *
     * @mbg.generated
     */
    public void setCounterTypeId(Integer counterTypeId) {
        this.counterTypeId = counterTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_type_recipe_category.recipe_category_id
     *
     * @return the value of dh_counter_type_recipe_category.recipe_category_id
     *
     * @mbg.generated
     */
    public Integer getRecipeCategoryId() {
        return recipeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_type_recipe_category.recipe_category_id
     *
     * @param recipeCategoryId the value for dh_counter_type_recipe_category.recipe_category_id
     *
     * @mbg.generated
     */
    public void setRecipeCategoryId(Integer recipeCategoryId) {
        this.recipeCategoryId = recipeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_type_recipe_category.create_time
     *
     * @return the value of dh_counter_type_recipe_category.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_type_recipe_category.create_time
     *
     * @param createTime the value for dh_counter_type_recipe_category.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_type_recipe_category.create_user
     *
     * @return the value of dh_counter_type_recipe_category.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_type_recipe_category.create_user
     *
     * @param createUser the value for dh_counter_type_recipe_category.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_type_recipe_category.update_time
     *
     * @return the value of dh_counter_type_recipe_category.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_type_recipe_category.update_time
     *
     * @param updateTime the value for dh_counter_type_recipe_category.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_type_recipe_category.update_user
     *
     * @return the value of dh_counter_type_recipe_category.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_type_recipe_category.update_user
     *
     * @param updateUser the value for dh_counter_type_recipe_category.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_type_recipe_category.safetyone
     *
     * @return the value of dh_counter_type_recipe_category.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_type_recipe_category.safetyone
     *
     * @param safetyone the value for dh_counter_type_recipe_category.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_type_recipe_category.safetytwo
     *
     * @return the value of dh_counter_type_recipe_category.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_type_recipe_category.safetytwo
     *
     * @param safetytwo the value for dh_counter_type_recipe_category.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }
}