package com.lswd.youpin.model.lsyp;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

public class CounterOrder {
    private List<CounterMenu> counterMenus;

    private String payTypeName;

    private String payTimeStr;

    public String getPayTimeStr() {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        payTimeStr = format.format(payTime);
        return payTimeStr;
    }

    public void setPayTimeStr(String payTimeStr) {
        this.payTimeStr = payTimeStr;
    }

    public String getPayTypeName() {
        return payTypeName;
    }

    public void setPayTypeName(String payTypeName) {
        this.payTypeName = payTypeName;
    }

    public List<CounterMenu> getCounterMenus() {
        return counterMenus;
    }

    public void setCounterMenus(List<CounterMenu> counterMenus) {
        this.counterMenus = counterMenus;
    }

    private List<CounterOrderItems> items;

    public List<CounterOrderItems> getItems() {
        return items;
    }

    public void setItems(List<CounterOrderItems> items) {
        this.items = items;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.order_name
     *
     * @mbg.generated
     */
    private String orderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.member_id
     *
     * @mbg.generated
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.member_name
     *
     * @mbg.generated
     */
    private String memberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.member_carduid
     *
     * @mbg.generated
     */
    private String memberCarduid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.counter_id
     *
     * @mbg.generated
     */
    private String counterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.receivable_amount
     *
     * @mbg.generated
     */
    private Float receivableAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.discount_amount
     *
     * @mbg.generated
     */
    private Float discountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.received_amount
     *
     * @mbg.generated
     */
    private Float receivedAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.balance
     *
     * @mbg.generated
     */
    private Float balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.pay_time
     *
     * @mbg.generated
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.pay_type
     *
     * @mbg.generated
     */
    private Short payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.number_table
     *
     * @mbg.generated
     */
    private Integer numberTable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.number_people
     *
     * @mbg.generated
     */
    private Integer numberPeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.counter_user
     *
     * @mbg.generated
     */
    private String counterUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_counter_order.safetythree
     *
     * @mbg.generated
     */
    private String safetythree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.id
     *
     * @return the value of dh_counter_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.id
     *
     * @param id the value for dh_counter_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.order_id
     *
     * @return the value of dh_counter_order.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.order_id
     *
     * @param orderId the value for dh_counter_order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.order_name
     *
     * @return the value of dh_counter_order.order_name
     *
     * @mbg.generated
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.order_name
     *
     * @param orderName the value for dh_counter_order.order_name
     *
     * @mbg.generated
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName == null ? null : orderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.member_id
     *
     * @return the value of dh_counter_order.member_id
     *
     * @mbg.generated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.member_id
     *
     * @param memberId the value for dh_counter_order.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.member_name
     *
     * @return the value of dh_counter_order.member_name
     *
     * @mbg.generated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.member_name
     *
     * @param memberName the value for dh_counter_order.member_name
     *
     * @mbg.generated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.member_carduid
     *
     * @return the value of dh_counter_order.member_carduid
     *
     * @mbg.generated
     */
    public String getMemberCarduid() {
        return memberCarduid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.member_carduid
     *
     * @param memberCarduid the value for dh_counter_order.member_carduid
     *
     * @mbg.generated
     */
    public void setMemberCarduid(String memberCarduid) {
        this.memberCarduid = memberCarduid == null ? null : memberCarduid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.counter_id
     *
     * @return the value of dh_counter_order.counter_id
     *
     * @mbg.generated
     */
    public String getCounterId() {
        return counterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.counter_id
     *
     * @param counterId the value for dh_counter_order.counter_id
     *
     * @mbg.generated
     */
    public void setCounterId(String counterId) {
        this.counterId = counterId == null ? null : counterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.receivable_amount
     *
     * @return the value of dh_counter_order.receivable_amount
     *
     * @mbg.generated
     */
    public Float getReceivableAmount() {
        return receivableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.receivable_amount
     *
     * @param receivableAmount the value for dh_counter_order.receivable_amount
     *
     * @mbg.generated
     */
    public void setReceivableAmount(Float receivableAmount) {
        this.receivableAmount = receivableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.discount_amount
     *
     * @return the value of dh_counter_order.discount_amount
     *
     * @mbg.generated
     */
    public Float getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.discount_amount
     *
     * @param discountAmount the value for dh_counter_order.discount_amount
     *
     * @mbg.generated
     */
    public void setDiscountAmount(Float discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.received_amount
     *
     * @return the value of dh_counter_order.received_amount
     *
     * @mbg.generated
     */
    public Float getReceivedAmount() {
        return receivedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.received_amount
     *
     * @param receivedAmount the value for dh_counter_order.received_amount
     *
     * @mbg.generated
     */
    public void setReceivedAmount(Float receivedAmount) {
        this.receivedAmount = receivedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.balance
     *
     * @return the value of dh_counter_order.balance
     *
     * @mbg.generated
     */
    public Float getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.balance
     *
     * @param balance the value for dh_counter_order.balance
     *
     * @mbg.generated
     */
    public void setBalance(Float balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.status
     *
     * @return the value of dh_counter_order.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.status
     *
     * @param status the value for dh_counter_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.pay_time
     *
     * @return the value of dh_counter_order.pay_time
     *
     * @mbg.generated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.pay_time
     *
     * @param payTime the value for dh_counter_order.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.pay_type
     *
     * @return the value of dh_counter_order.pay_type
     *
     * @mbg.generated
     */
    public Short getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.pay_type
     *
     * @param payType the value for dh_counter_order.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(Short payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.number_table
     *
     * @return the value of dh_counter_order.number_table
     *
     * @mbg.generated
     */
    public Integer getNumberTable() {
        return numberTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.number_table
     *
     * @param numberTable the value for dh_counter_order.number_table
     *
     * @mbg.generated
     */
    public void setNumberTable(Integer numberTable) {
        this.numberTable = numberTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.number_people
     *
     * @return the value of dh_counter_order.number_people
     *
     * @mbg.generated
     */
    public Integer getNumberPeople() {
        return numberPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.number_people
     *
     * @param numberPeople the value for dh_counter_order.number_people
     *
     * @mbg.generated
     */
    public void setNumberPeople(Integer numberPeople) {
        this.numberPeople = numberPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.description
     *
     * @return the value of dh_counter_order.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.description
     *
     * @param description the value for dh_counter_order.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.counter_user
     *
     * @return the value of dh_counter_order.counter_user
     *
     * @mbg.generated
     */
    public String getCounterUser() {
        return counterUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.counter_user
     *
     * @param counterUser the value for dh_counter_order.counter_user
     *
     * @mbg.generated
     */
    public void setCounterUser(String counterUser) {
        this.counterUser = counterUser == null ? null : counterUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.create_time
     *
     * @return the value of dh_counter_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.create_time
     *
     * @param createTime the value for dh_counter_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.update_time
     *
     * @return the value of dh_counter_order.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.update_time
     *
     * @param updateTime the value for dh_counter_order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_counter_order.safetythree
     *
     * @return the value of dh_counter_order.safetythree
     *
     * @mbg.generated
     */
    public String getSafetythree() {
        return safetythree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_counter_order.safetythree
     *
     * @param safetythree the value for dh_counter_order.safetythree
     *
     * @mbg.generated
     */
    public void setSafetythree(String safetythree) {
        this.safetythree = safetythree == null ? null : safetythree.trim();
    }
}