package com.lswd.youpin.model.lsyp;

import java.util.Date;

public class DiskRecipe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_recipe.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_recipe.canteenid
     *
     * @mbg.generated
     */
    private String canteenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_recipe.disktypeid
     *
     * @mbg.generated
     */
    private Integer diskTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_recipe.breakfast
     *
     * @mbg.generated
     */
    private String breakfast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_recipe.lunch
     *
     * @mbg.generated
     */
    private String lunch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_recipe.dinner
     *
     * @mbg.generated
     */
    private String dinner;

    private String breakfastName;

    private String lunchName;

    private String dinnerName;

    private String diskName;

    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_recipe.recipetime
     *
     * @mbg.generated
     */
    private Date recipeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_recipe.createtime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_disk_recipe.id
     *
     * @return the value of dh_disk_recipe.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_disk_recipe.id
     *
     * @param id the value for dh_disk_recipe.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_disk_recipe.canteenid
     *
     * @return the value of dh_disk_recipe.canteenid
     *
     * @mbg.generated
     */
    public String getCanteenId() {
        return canteenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_disk_recipe.canteenid
     *
     * @param canteenId the value for dh_disk_recipe.canteenid
     *
     * @mbg.generated
     */
    public void setCanteenId(String canteenId) {
        this.canteenId = canteenId == null ? null : canteenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_disk_recipe.breakfast
     *
     * @return the value of dh_disk_recipe.breakfast
     *
     * @mbg.generated
     */
    public String getBreakfast() {
        return breakfast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_disk_recipe.breakfast
     *
     * @param breakfast the value for dh_disk_recipe.breakfast
     *
     * @mbg.generated
     */
    public void setBreakfast(String breakfast) {
        this.breakfast = breakfast == null ? null : breakfast.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_disk_recipe.lunch
     *
     * @return the value of dh_disk_recipe.lunch
     *
     * @mbg.generated
     */
    public String getLunch() {
        return lunch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_disk_recipe.lunch
     *
     * @param lunch the value for dh_disk_recipe.lunch
     *
     * @mbg.generated
     */
    public void setLunch(String lunch) {
        this.lunch = lunch == null ? null : lunch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_disk_recipe.dinner
     *
     * @return the value of dh_disk_recipe.dinner
     *
     * @mbg.generated
     */
    public String getDinner() {
        return dinner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_disk_recipe.dinner
     *
     * @param dinner the value for dh_disk_recipe.dinner
     *
     * @mbg.generated
     */
    public void setDinner(String dinner) {
        this.dinner = dinner == null ? null : dinner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_disk_recipe.createtime
     *
     * @return the value of dh_disk_recipe.createtime
     *
     * @mbg.generated
     */
    public String getBreakfastName() {
        return breakfastName;
    }

    public void setBreakfastName(String breakfastName) {
        this.breakfastName = breakfastName;
    }

    public String getLunchName() {
        return lunchName;
    }

    public void setLunchName(String lunchName) {
        this.lunchName = lunchName;
    }

    public String getDinnerName() {
        return dinnerName;
    }

    public void setDinnerName(String dinnerName) {
        this.dinnerName = dinnerName;
    }

    public String getDiskName() {
        return diskName;
    }

    public void setDiskName(String diskName) {
        this.diskName = diskName;
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public Integer getDiskTypeId() {
        return diskTypeId;
    }

    public void setDiskTypeId(Integer diskTypeId) {
        this.diskTypeId = diskTypeId;
    }

    public Date getRecipeTime() {
        return recipeTime;
    }

    public void setRecipeTime(Date recipeTime) {
        this.recipeTime = recipeTime;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}