package com.lswd.youpin.model.lsyp;

import java.util.Date;

public class DiskLabel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_label.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_label.labeluid
     *
     * @mbg.generated
     */
    private String labeluid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_label.canteenid
     *
     * @mbg.generated
     */
    private String canteenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_label.recipeid
     *
     * @mbg.generated
     */
    private String recipeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_label.disktypeid
     *
     * @mbg.generated
     */
    private Integer disktypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_label.exw_time
     *
     * @mbg.generated
     */
    private Date exwTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_label.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_label.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_disk_label.valid
     *
     * @mbg.generated
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_disk_label.id
     *
     * @return the value of dh_disk_label.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_disk_label.id
     *
     * @param id the value for dh_disk_label.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_disk_label.labeluid
     *
     * @return the value of dh_disk_label.labeluid
     *
     * @mbg.generated
     */
    public String getLabeluid() {
        return labeluid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_disk_label.labeluid
     *
     * @param labeluid the value for dh_disk_label.labeluid
     *
     * @mbg.generated
     */
    public void setLabeluid(String labeluid) {
        this.labeluid = labeluid == null ? null : labeluid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_disk_label.canteenid
     *
     * @return the value of dh_disk_label.canteenid
     *
     * @mbg.generated
     */
    public String getCanteenid() {
        return canteenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_disk_label.canteenid
     *
     * @param canteenid the value for dh_disk_label.canteenid
     *
     * @mbg.generated
     */
    public void setCanteenid(String canteenid) {
        this.canteenid = canteenid == null ? null : canteenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_disk_label.recipeid
     *
     * @return the value of dh_disk_label.recipeid
     *
     * @mbg.generated
     */
    public String getRecipeid() {
        return recipeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_disk_label.recipeid
     *
     * @param recipeid the value for dh_disk_label.recipeid
     *
     * @mbg.generated
     */
    public void setRecipeid(String recipeid) {
        this.recipeid = recipeid == null ? null : recipeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_disk_label.disktypeid
     *
     * @return the value of dh_disk_label.disktypeid
     *
     * @mbg.generated
     */
    public Integer getDisktypeid() {
        return disktypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_disk_label.disktypeid
     *
     * @param disktypeid the value for dh_disk_label.disktypeid
     *
     * @mbg.generated
     */
    public void setDisktypeid(Integer disktypeid) {
        this.disktypeid = disktypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_disk_label.exw_time
     *
     * @return the value of dh_disk_label.exw_time
     *
     * @mbg.generated
     */
    public Date getExwTime() {
        return exwTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_disk_label.exw_time
     *
     * @param exwTime the value for dh_disk_label.exw_time
     *
     * @mbg.generated
     */
    public void setExwTime(Date exwTime) {
        this.exwTime = exwTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_disk_label.start_time
     *
     * @return the value of dh_disk_label.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_disk_label.start_time
     *
     * @param startTime the value for dh_disk_label.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_disk_label.end_time
     *
     * @return the value of dh_disk_label.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_disk_label.end_time
     *
     * @param endTime the value for dh_disk_label.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_disk_label.valid
     *
     * @return the value of dh_disk_label.valid
     *
     * @mbg.generated
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_disk_label.valid
     *
     * @param valid the value for dh_disk_label.valid
     *
     * @mbg.generated
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}