package com.lswd.youpin.model.lsyp;

import java.text.SimpleDateFormat;
import java.util.Date;

public class Employee {

    private String educationName;

    public String getEducationName() {
        return educationName;
    }

    public void setEducationName(String educationName) {
        this.educationName = educationName;
    }

    private String regionName;

    public String getRegionName() {
        return regionName;
    }

    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    public Employee() {
    }

    public Employee(String employeeName, String regionId, Boolean sex, Date birthday, Short status, String duty, String telephone,
                    String job, Date packStartTime, Boolean isDelete, String updateUser, Date updateTime, Date createTime, String cardNumber) {
        this.employeeName = employeeName;
        this.regionId = regionId;
        this.sex = sex;
        this.birthday = birthday;
        this.status = status;
        this.duty = duty;
        this.telephone = telephone;
        this.job = job;
        this.packStartTime = packStartTime;
        this.isDelete = isDelete;
        this.updateUser = updateUser;
        this.updateTime = updateTime;
        this.createTime = createTime;
        this.cardNumber = cardNumber;
    }

    private String statusName;//状态名称
    private String sexName;//性别
    private String birthdayString;//生日，字符串类型
    private String packStartTimeString;//入职时间，字符串类型
    private String updateTimeString;//更新时间，字符串类型
    private String createTimeString;//创建时间，字符串类型
    private String departmentName;//部门名称


    public String getStatusName() {
        return statusName;
    }
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }
    public String getSexName() {
        return sexName;
    }
    public void setSexName(String sexName) {
        this.sexName = sexName;
    }
    public String getDepartmentName() {
        return departmentName;
    }
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    public String getBirthdayString() {return birthdayString;}
    public void setBirthdayString(String birthdayString) {this.birthdayString = birthdayString;}
    public String getPackStartTimeString() {return packStartTimeString;}
    public void setPackStartTimeString(String packStartTimeString) {this.packStartTimeString = packStartTimeString;}
    public String getUpdateTimeString() {return updateTimeString;}
    public void setUpdateTimeString(String updateTimeString) {this.updateTimeString = updateTimeString;}
    public String getCreateTimeString() {return createTimeString;}
    public void setCreateTimeString(String createTimeString) {this.createTimeString = createTimeString;}


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_id
     *
     * @mbg.generated
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_name
     *
     * @mbg.generated
     */
    private String employeeName="";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.department_id
     *
     * @mbg.generated
     */
    private String regionId="";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.sex
     *
     * @mbg.generated
     */
    private Boolean sex=true;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.birthday
     *
     * @mbg.generated
     */
    private Date birthday=new Date();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.job
     *
     * @mbg.generated
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.pack_start_time
     *
     * @mbg.generated
     */
    private Date packStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.satetytwo
     *
     * @mbg.generated
     */
    private String satetytwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.safetythree
     *
     * @mbg.generated
     */
    private String safetythree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.id
     *
     * @return the value of t_employee.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.id
     *
     * @param id the value for t_employee.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_id
     *
     * @return the value of t_employee.employee_id
     *
     * @mbg.generated
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_id
     *
     * @param employeeId the value for t_employee.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_name
     *
     * @return the value of t_employee.employee_name
     *
     * @mbg.generated
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_name
     *
     * @param employeeName the value for t_employee.employee_name
     *
     * @mbg.generated
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.department_id
     *
     * @return the value of t_employee.department_id
     *
     * @mbg.generated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.department_id
     *
     * @param departmentId the value for t_employee.department_id
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.sex
     *
     * @return the value of t_employee.sex
     *
     * @mbg.generated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.sex
     *
     * @param sex the value for t_employee.sex
     *
     * @mbg.generated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.birthday
     *
     * @return the value of t_employee.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.birthday
     *
     * @param birthday the value for t_employee.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.status
     *
     * @return the value of t_employee.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.status
     *
     * @param status the value for t_employee.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.duty
     *
     * @return the value of t_employee.duty
     *
     * @mbg.generated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.duty
     *
     * @param duty the value for t_employee.duty
     *
     * @mbg.generated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.telephone
     *
     * @return the value of t_employee.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.telephone
     *
     * @param telephone the value for t_employee.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.job
     *
     * @return the value of t_employee.job
     *
     * @mbg.generated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.job
     *
     * @param job the value for t_employee.job
     *
     * @mbg.generated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.pack_start_time
     *
     * @return the value of t_employee.pack_start_time
     *
     * @mbg.generated
     */
    public Date getPackStartTime() {
        return packStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.pack_start_time
     *
     * @param packStartTime the value for t_employee.pack_start_time
     *
     * @mbg.generated
     */
    public void setPackStartTime(Date packStartTime) {
        this.packStartTime = packStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.is_delete
     *
     * @return the value of t_employee.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.is_delete
     *
     * @param isDelete the value for t_employee.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.update_user
     *
     * @return the value of t_employee.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.update_user
     *
     * @param updateUser the value for t_employee.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.update_time
     *
     * @return the value of t_employee.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.update_time
     *
     * @param updateTime the value for t_employee.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.create_time
     *
     * @return the value of t_employee.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.create_time
     *
     * @param createTime the value for t_employee.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.safetyone
     *
     * @return the value of t_employee.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.safetyone
     *
     * @param safetyone the value for t_employee.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.satetytwo
     *
     * @return the value of t_employee.satetytwo
     *
     * @mbg.generated
     */
    public String getSatetytwo() {
        return satetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.satetytwo
     *
     * @param satetytwo the value for t_employee.satetytwo
     *
     * @mbg.generated
     */
    public void setSatetytwo(String satetytwo) {
        this.satetytwo = satetytwo == null ? null : satetytwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.safetythree
     *
     * @return the value of t_employee.safetythree
     *
     * @mbg.generated
     */
    public String getSafetythree() {
        return safetythree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.safetythree
     *
     * @param safetythree the value for t_employee.safetythree
     *
     * @mbg.generated
     */
    public void setSafetythree(String safetythree) {
        this.safetythree = safetythree == null ? null : safetythree.trim();
    }

    private String state;

    public String getState() {return state;}

    public void setState(String state) {this.state = state;}

    public String getRegionId() {return regionId;}

    public void setRegionId(String regionId) {this.regionId = regionId;}

    private String cardNumber="";

    private String political="";

    private String major="";

    private String company="";

    private String weixin="";

    private String email="";

    private String qq="";

    private String nation="";

    private String school="";

    private Integer education=3;

    public String getCardNumber() {return cardNumber;}

    public String getPolitical() {return political;}

    public String getMajor() {return major;}

    public String getCompany() {return company;}

    public String getWeixin() {return weixin;}

    public String getEmail() {return email;}

    public String getQq() {return qq;}

    public String getNation() {return nation;}

    public String getSchool() {return school;}

    public Integer getEducation() {return education;}

    public void setCardNumber(String cardNumber) {this.cardNumber = cardNumber;}

    public void setPolitical(String political) {this.political = political;}

    public void setMajor(String major) {this.major = major;}

    public void setCompany(String company) {this.company = company;}

    public void setWeixin(String weixin) {this.weixin = weixin;}

    public void setEmail(String email) {this.email = email;}

    public void setQq(String qq) {this.qq = qq;}

    public void setNation(String nation) {this.nation = nation;}

    public void setSchool(String school) {this.school = school;}

    public void setEducation(Integer education) {this.education = education;}


}