package com.lswd.youpin.model.lsyp;

import java.util.Date;
import java.util.List;

public class GoodPlan {

    private String canteenName;
    private String date;
    private String weekday;
    private List<GoodPlanItems> goodPlanItemses;
    private String statusName;

    public String getCanteenName() {
        return canteenName;
    }

    public void setCanteenName(String canteenName) {
        this.canteenName = canteenName;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getWeekday() {
        return weekday;
    }

    public void setWeekday(String weekday) {
        this.weekday = weekday;
    }

    public void setGoodPlanItemses(List<GoodPlanItems> goodPlanItemses) {
        this.goodPlanItemses = goodPlanItemses;
    }

    public List<GoodPlanItems> getGoodPlanItemses() {
        return goodPlanItemses;
    }

    public String getStatusName() {
        return statusName;
    }

    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_plan.id
     *
     * @mbg.generated
     */
    private Integer id;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_plan.good_plan_id
     *
     * @mbg.generated
     */
    private String goodPlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_plan.is_delete
     *
     * @mbg.generated
     */

    private String canteenId;
    public String getCanteenId() {
        return canteenId;
    }
    public void setCanteenId(String canteenId) {
        this.canteenId = canteenId;
    }

    private Date pickingTime;
    private String comment;

    public Boolean getDelete() {
        return isDelete;
    }

    public void setDelete(Boolean delete) {
        isDelete = delete;
    }

    public Date getPickingTime() {
        return pickingTime;
    }

    public void setPickingTime(Date pickingTime) {
        this.pickingTime = pickingTime;
    }

    public String getComment() {
        return comment;
    }
    public void setComment(String comment) {
        this.comment = comment;
    }

    private Boolean isDelete = false;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_plan.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_plan.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_plan.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_plan.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_plan.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_plan.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_plan.id
     *
     * @return the value of t_good_plan.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_plan.id
     *
     * @param id the value for t_good_plan.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_plan.good_plan_id
     *
     * @return the value of t_good_plan.good_plan_id
     *
     * @mbg.generated
     */
    public String getGoodPlanId() {
        return goodPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_plan.good_plan_id
     *
     * @param goodPlanId the value for t_good_plan.good_plan_id
     *
     * @mbg.generated
     */
    public void setGoodPlanId(String goodPlanId) {
        this.goodPlanId = goodPlanId == null ? null : goodPlanId.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_plan.create_user
     *
     * @return the value of t_good_plan.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_plan.create_user
     *
     * @param createUser the value for t_good_plan.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_plan.update_user
     *
     * @return the value of t_good_plan.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_plan.update_user
     *
     * @param updateUser the value for t_good_plan.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_plan.create_time
     *
     * @return the value of t_good_plan.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_plan.create_time
     *
     * @param createTime the value for t_good_plan.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_plan.update_time
     *
     * @return the value of t_good_plan.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_plan.update_time
     *
     * @param updateTime the value for t_good_plan.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_plan.safetyone
     *
     * @return the value of t_good_plan.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_plan.safetyone
     *
     * @param safetyone the value for t_good_plan.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_plan.safetytwo
     *
     * @return the value of t_good_plan.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_plan.safetytwo
     *
     * @param safetytwo the value for t_good_plan.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }
}