package com.lswd.youpin.model.lsyp;

import com.lswd.youpin.model.Associator;

import java.util.Date;
import java.util.List;

public class GoodOrder {


    private String createTimeString;
    private String pickintTimeInterval;
    private Associator associator;
    private String statusName;
    private Boolean isComment;
    private String canteenTEL;
    private String canteenName;
    private String canteenAddress;
    private String canteenLogo;
    private String canteenLeader;
    private List<GoodOrderItems> goodOrderItemses;
    private String associatorName;
    private String associatorTel;
    private String payTypeName;
    private Boolean gOrRFlag = true;

    public String getAssociatorTel() {
        return associatorTel;
    }

    public void setAssociatorTel(String associatorTel) {
        this.associatorTel = associatorTel;
    }

    public String getPickintTimeInterval() {
        return pickintTimeInterval;
    }

    public void setPickintTimeInterval(String pickintTimeInterval) {
        this.pickintTimeInterval = pickintTimeInterval;
    }

    public Associator getAssociator() {
        return associator;
    }

    public void setAssociator(Associator associator) {
        this.associator = associator;
    }

    public String getCreateTimeString() {
        return createTimeString;
    }

    public void setCreateTimeString(String createTimeString) {
        this.createTimeString = createTimeString;
    }

    public String getCanteenLeader() {
        return canteenLeader;
    }

    public void setCanteenLeader(String canteenLeader) {
        this.canteenLeader = canteenLeader;
    }

    public String getCanteenLogo() {
        return canteenLogo;
    }

    public void setCanteenLogo(String canteenLogo) {
        this.canteenLogo = canteenLogo;
    }

    public Boolean getgOrRFlag() {
        return gOrRFlag;
    }

    public void setgOrRFlag(Boolean gOrRFlag) {
        this.gOrRFlag = gOrRFlag;
    }

    public String getStatusName() {
        return statusName;
    }

    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    public Boolean getComment() {
        return isComment;
    }

    public void setComment(Boolean comment) {
        isComment = comment;
    }

    public String getCanteenTEL() {
        return canteenTEL;
    }

    public void setCanteenTEL(String canteenTEL) {
        this.canteenTEL = canteenTEL;
    }

    public String getCanteenName() {
        return canteenName;
    }

    public void setCanteenName(String canteenName) {
        this.canteenName = canteenName;
    }

    public String getCanteenAddress() {
        return canteenAddress;
    }

    public void setCanteenAddress(String canteenAddress) {
        this.canteenAddress = canteenAddress;
    }


    public String getPayTypeName() {
        return payTypeName;
    }

    public void setPayTypeName(String payTypeName) {
        this.payTypeName = payTypeName;
    }



    public String getAssociatorName() {
        return associatorName;
    }

    public void setAssociatorName(String associatorName) {
        this.associatorName = associatorName;
    }

    public List<GoodOrderItems> getGoodOrderItemses() {
        return goodOrderItemses;
    }
    public void setGoodOrderItemses(List<GoodOrderItems> goodOrderItemses) {
        this.goodOrderItemses = goodOrderItemses;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_order_over.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_order_over.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_order_over.associator_id
     *
     * @mbg.generated
     */
    private String associatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_order_over.picking_time
     *
     * @mbg.generated
     */
    private Date pickingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_order_over.order_amount
     *
     * @mbg.generated
     */
    private Float orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_order_over.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_order_over.canteen_id
     *
     * @mbg.generated
     */
    private String canteenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_order_over.pay_type
     *
     * @mbg.generated
     */
    private Short payType = 0;

    /**
     *
     */
    private List<GoodOrderItems> goodOrderItems;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_order_over.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_order_over.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_order_over.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_order_over.safetyone
     *
     * @mbg.generated
     */
    private Integer unifiedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_order_over.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_order_over.safetythree
     *
     * @mbg.generated
     */
    private String safetythree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_order_over.id
     *
     * @return the value of t_good_order_over.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_order_over.id
     *
     * @param id the value for t_good_order_over.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_order_over.order_id
     *
     * @return the value of t_good_order_over.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_order_over.order_id
     *
     * @param orderId the value for t_good_order_over.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_order_over.associator_id
     *
     * @return the value of t_good_order_over.associator_id
     *
     * @mbg.generated
     */
    public String getAssociatorId() {
        return associatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_order_over.associator_id
     *
     * @param associatorId the value for t_good_order_over.associator_id
     *
     * @mbg.generated
     */
    public void setAssociatorId(String associatorId) {
        this.associatorId = associatorId == null ? null : associatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_order_over.picking_time
     *
     * @return the value of t_good_order_over.picking_time
     *
     * @mbg.generated
     */
    public List<GoodOrderItems> getGoodOrderItems() {return goodOrderItems;}
    public Date getPickingTime() {
        return pickingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_order_over.picking_time
     *
     * @param pickingTime the value for t_good_order_over.picking_time
     *
     * @mbg.generated
     */
    public void setPickingTime(Date pickingTime) {
        this.pickingTime = pickingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_order_over.order_amount
     *
     * @return the value of t_good_order_over.order_amount
     *
     * @mbg.generated
     */
    public Float getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_order_over.order_amount
     *
     * @param orderAmount the value for t_good_order_over.order_amount
     *
     * @mbg.generated
     */
    public void setOrderAmount(Float orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_order_over.status
     *
     * @return the value of t_good_order_over.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_order_over.status
     *
     * @param status the value for t_good_order_over.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_order_over.canteen_id
     *
     * @return the value of t_good_order_over.canteen_id
     *
     * @mbg.generated
     */
    public String getCanteenId() {
        return canteenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_order_over.canteen_id
     *
     * @param canteenId the value for t_good_order_over.canteen_id
     *
     * @mbg.generated
     */
    public void setCanteenId(String canteenId) {
        this.canteenId = canteenId == null ? null : canteenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_order_over.pay_type
     *
     * @return the value of t_good_order_over.pay_type
     *
     * @mbg.generated
     */
    public Short getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_order_over.pay_type
     *
     * @param payType the value for t_good_order_over.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(Short payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_order_over.description
     *
     * @return the value of t_good_order_over.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_order_over.description
     *
     * @param description the value for t_good_order_over.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_order_over.create_time
     *
     * @return the value of t_good_order_over.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_order_over.create_time
     *
     * @param createTime the value for t_good_order_over.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_order_over.update_time
     *
     * @return the value of t_good_order_over.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_order_over.update_time
     *
     * @param updateTime the value for t_good_order_over.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_order_over.safetytwo
     *
     * @return the value of t_good_order_over.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_order_over.safetytwo
     *
     * @param safetytwo the value for t_good_order_over.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_order_over.safetythree
     *
     * @return the value of t_good_order_over.safetythree
     *
     * @mbg.generated
     */
    public String getSafetythree() {
        return safetythree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_order_over.safetythree
     *
     * @param safetythree the value for t_good_order_over.safetythree
     *
     * @mbg.generated
     */
    public void setSafetythree(String safetythree) {
        this.safetythree = safetythree == null ? null : safetythree.trim();
    }
    public void setGoodOrderItems(List<GoodOrderItems> goodOrderItems) {this.goodOrderItems = goodOrderItems;}

    public Integer getUnifiedId() {
        return unifiedId;
    }

    public void setUnifiedId(Integer unifiedId) {
        this.unifiedId = unifiedId;
    }
    private Double outFee;

    public Double getOutFee() {return outFee;}

    public void setOutFee(Double outFee) {this.outFee = outFee;}
}