package com.lswd.youpin.model.lsyp;

public class GoodAttribute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_attribute.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_attribute.energy
     *
     * @mbg.generated
     */
    private Float energy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_attribute.protein
     *
     * @mbg.generated
     */
    private Float protein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_attribute.carbohydrate
     *
     * @mbg.generated
     */
    private Float carbohydrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_attribute.fats
     *
     * @mbg.generated
     */
    private Float fats;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_attribute.vitaminA
     *
     * @mbg.generated
     */
    private Float vitamina;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_attribute.vitaminB1
     *
     * @mbg.generated
     */
    private Float vitaminb1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_attribute.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_attribute.shape
     *
     * @mbg.generated
     */
    private String shape;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_attribute.good_id
     *
     * @mbg.generated
     */
    private String goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_attribute.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_attribute.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_attribute.safetythree
     *
     * @mbg.generated
     */
    private String safetythree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_attribute.id
     *
     * @return the value of t_good_attribute.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_attribute.id
     *
     * @param id the value for t_good_attribute.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_attribute.energy
     *
     * @return the value of t_good_attribute.energy
     *
     * @mbg.generated
     */
    public Float getEnergy() {
        return energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_attribute.energy
     *
     * @param energy the value for t_good_attribute.energy
     *
     * @mbg.generated
     */
    public void setEnergy(Float energy) {
        this.energy = energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_attribute.protein
     *
     * @return the value of t_good_attribute.protein
     *
     * @mbg.generated
     */
    public Float getProtein() {
        return protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_attribute.protein
     *
     * @param protein the value for t_good_attribute.protein
     *
     * @mbg.generated
     */
    public void setProtein(Float protein) {
        this.protein = protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_attribute.carbohydrate
     *
     * @return the value of t_good_attribute.carbohydrate
     *
     * @mbg.generated
     */
    public Float getCarbohydrate() {
        return carbohydrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_attribute.carbohydrate
     *
     * @param carbohydrate the value for t_good_attribute.carbohydrate
     *
     * @mbg.generated
     */
    public void setCarbohydrate(Float carbohydrate) {
        this.carbohydrate = carbohydrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_attribute.fats
     *
     * @return the value of t_good_attribute.fats
     *
     * @mbg.generated
     */
    public Float getFats() {
        return fats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_attribute.fats
     *
     * @param fats the value for t_good_attribute.fats
     *
     * @mbg.generated
     */
    public void setFats(Float fats) {
        this.fats = fats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_attribute.vitaminA
     *
     * @return the value of t_good_attribute.vitaminA
     *
     * @mbg.generated
     */
    public Float getVitamina() {
        return vitamina;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_attribute.vitaminA
     *
     * @param vitamina the value for t_good_attribute.vitaminA
     *
     * @mbg.generated
     */
    public void setVitamina(Float vitamina) {
        this.vitamina = vitamina;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_attribute.vitaminB1
     *
     * @return the value of t_good_attribute.vitaminB1
     *
     * @mbg.generated
     */
    public Float getVitaminb1() {
        return vitaminb1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_attribute.vitaminB1
     *
     * @param vitaminb1 the value for t_good_attribute.vitaminB1
     *
     * @mbg.generated
     */
    public void setVitaminb1(Float vitaminb1) {
        this.vitaminb1 = vitaminb1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_attribute.color
     *
     * @return the value of t_good_attribute.color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_attribute.color
     *
     * @param color the value for t_good_attribute.color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_attribute.shape
     *
     * @return the value of t_good_attribute.shape
     *
     * @mbg.generated
     */
    public String getShape() {
        return shape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_attribute.shape
     *
     * @param shape the value for t_good_attribute.shape
     *
     * @mbg.generated
     */
    public void setShape(String shape) {
        this.shape = shape == null ? null : shape.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_attribute.good_id
     *
     * @return the value of t_good_attribute.good_id
     *
     * @mbg.generated
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_attribute.good_id
     *
     * @param goodId the value for t_good_attribute.good_id
     *
     * @mbg.generated
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId == null ? null : goodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_attribute.safetyone
     *
     * @return the value of t_good_attribute.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_attribute.safetyone
     *
     * @param safetyone the value for t_good_attribute.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_attribute.safetytwo
     *
     * @return the value of t_good_attribute.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_attribute.safetytwo
     *
     * @param safetytwo the value for t_good_attribute.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_attribute.safetythree
     *
     * @return the value of t_good_attribute.safetythree
     *
     * @mbg.generated
     */
    public String getSafetythree() {
        return safetythree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_attribute.safetythree
     *
     * @param safetythree the value for t_good_attribute.safetythree
     *
     * @mbg.generated
     */
    public void setSafetythree(String safetythree) {
        this.safetythree = safetythree == null ? null : safetythree.trim();
    }
}