package com.lswd.youpin.model.lsyp;



public class GoodPlanItems {

    private boolean isHot = false;//是否热销
    private float priceDay;//当天售卖价格
    private float marketPriceDay;//当天市场价格
    private Integer surplus = 0;//库存，默认为99
    private Good good;


    public boolean isHot() {
        return isHot;
    }

    public void setHot(boolean hot) {
        isHot = hot;
    }

    public float getPriceDay() {
        return priceDay;
    }

    public void setPriceDay(float priceDay) {
        this.priceDay = priceDay;
    }

    public float getMarketPriceDay() {
        return marketPriceDay;
    }

    public void setMarketPriceDay(float marketPriceDay) {
        this.marketPriceDay = marketPriceDay;
    }

    public Good getGood() {
        return good;
    }

    public void setGood(Good good) {
        this.good = good;
    }

    public Integer getSurplus() {
        return surplus;
    }

    public void setSurplus(Integer surplus) {
        this.surplus = surplus;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_planitems.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_planitems.good_id
     *
     * @mbg.generated
     */
    private String goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_planitems.good_plan_id
     *
     * @mbg.generated
     */
    private String goodPlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_planitems.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete  = false;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_planitems.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_planitems.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_planitems.id
     *
     * @return the value of t_good_planitems.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_planitems.id
     *
     * @param id the value for t_good_planitems.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_planitems.good_id
     *
     * @return the value of t_good_planitems.good_id
     *
     * @mbg.generated
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_planitems.good_id
     *
     * @param goodId the value for t_good_planitems.good_id
     *
     * @mbg.generated
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId == null ? null : goodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_planitems.good_plan_id
     *
     * @return the value of t_good_planitems.good_plan_id
     *
     * @mbg.generated
     */
    public String getGoodPlanId() {
        return goodPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_planitems.good_plan_id
     *
     * @param goodPlanId the value for t_good_planitems.good_plan_id
     *
     * @mbg.generated
     */
    public void setGoodPlanId(String goodPlanId) {
        this.goodPlanId = goodPlanId == null ? null : goodPlanId.trim();
    }


    public Boolean getDelete() {
        return isDelete;
    }

    public void setDelete(Boolean delete) {
        isDelete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_planitems.safetyone
     *
     * @return the value of t_good_planitems.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_planitems.safetyone
     *
     * @param safetyone the value for t_good_planitems.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_planitems.safetytwo
     *
     * @return the value of t_good_planitems.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_planitems.safetytwo
     *
     * @param safetytwo the value for t_good_planitems.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }
}