package com.lswd.youpin.model.lsyp;

public class Ingredient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_ingredient.ingredientid
     *
     * @mbg.generated
     */
    private Integer ingredientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_ingredient.ingredientname
     *
     * @mbg.generated
     */
    private String ingredientname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_ingredient.menuid
     *
     * @mbg.generated
     */
    private String menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_ingredient.nutritionid
     *
     * @mbg.generated
     */
    private Integer nutritionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_ingredient.amount
     *
     * @mbg.generated
     */
    private Float amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_ingredient.isupload
     *
     * @mbg.generated
     */
    private Byte isupload;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_ingredient.ingredientid
     *
     * @return the value of dh_ingredient.ingredientid
     *
     * @mbg.generated
     */
    public Integer getIngredientid() {
        return ingredientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_ingredient.ingredientid
     *
     * @param ingredientid the value for dh_ingredient.ingredientid
     *
     * @mbg.generated
     */
    public void setIngredientid(Integer ingredientid) {
        this.ingredientid = ingredientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_ingredient.ingredientname
     *
     * @return the value of dh_ingredient.ingredientname
     *
     * @mbg.generated
     */
    public String getIngredientname() {
        return ingredientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_ingredient.ingredientname
     *
     * @param ingredientname the value for dh_ingredient.ingredientname
     *
     * @mbg.generated
     */
    public void setIngredientname(String ingredientname) {
        this.ingredientname = ingredientname == null ? null : ingredientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_ingredient.menuid
     *
     * @return the value of dh_ingredient.menuid
     *
     * @mbg.generated
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_ingredient.menuid
     *
     * @param menuid the value for dh_ingredient.menuid
     *
     * @mbg.generated
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid == null ? null : menuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_ingredient.nutritionid
     *
     * @return the value of dh_ingredient.nutritionid
     *
     * @mbg.generated
     */
    public Integer getNutritionid() {
        return nutritionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_ingredient.nutritionid
     *
     * @param nutritionid the value for dh_ingredient.nutritionid
     *
     * @mbg.generated
     */
    public void setNutritionid(Integer nutritionid) {
        this.nutritionid = nutritionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_ingredient.amount
     *
     * @return the value of dh_ingredient.amount
     *
     * @mbg.generated
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_ingredient.amount
     *
     * @param amount the value for dh_ingredient.amount
     *
     * @mbg.generated
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_ingredient.isupload
     *
     * @return the value of dh_ingredient.isupload
     *
     * @mbg.generated
     */
    public Byte getIsupload() {
        return isupload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_ingredient.isupload
     *
     * @param isupload the value for dh_ingredient.isupload
     *
     * @mbg.generated
     */
    public void setIsupload(Byte isupload) {
        this.isupload = isupload;
    }
}