package com.lswd.youpin.model.lsyp;

import java.util.Date;

public class JSPlatform {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_js_platform.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_js_platform.js_platform_id
     *
     * @mbg.generated
     */
    private String jsPlatformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_js_platform.js_platform_name
     *
     * @mbg.generated
     */
    private String jsPlatformName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_js_platform.canteen_id
     *
     * @mbg.generated
     */
    private String canteenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_js_platform.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_js_platform.imageurl
     *
     * @mbg.generated
     */
    private String imageurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_js_platform.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_js_platform.is_delete
     *
     * @mbg.generated
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_js_platform.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_js_platform.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_js_platform.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_js_platform.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_js_platform.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_js_platform.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_js_platform.id
     *
     * @return the value of dh_js_platform.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_js_platform.id
     *
     * @param id the value for dh_js_platform.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_js_platform.js_platform_id
     *
     * @return the value of dh_js_platform.js_platform_id
     *
     * @mbg.generated
     */
    public String getJsPlatformId() {
        return jsPlatformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_js_platform.js_platform_id
     *
     * @param jsPlatformId the value for dh_js_platform.js_platform_id
     *
     * @mbg.generated
     */
    public void setJsPlatformId(String jsPlatformId) {
        this.jsPlatformId = jsPlatformId == null ? null : jsPlatformId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_js_platform.js_platform_name
     *
     * @return the value of dh_js_platform.js_platform_name
     *
     * @mbg.generated
     */
    public String getJsPlatformName() {
        return jsPlatformName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_js_platform.js_platform_name
     *
     * @param jsPlatformName the value for dh_js_platform.js_platform_name
     *
     * @mbg.generated
     */
    public void setJsPlatformName(String jsPlatformName) {
        this.jsPlatformName = jsPlatformName == null ? null : jsPlatformName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_js_platform.canteen_id
     *
     * @return the value of dh_js_platform.canteen_id
     *
     * @mbg.generated
     */
    public String getCanteenId() {
        return canteenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_js_platform.canteen_id
     *
     * @param canteenId the value for dh_js_platform.canteen_id
     *
     * @mbg.generated
     */
    public void setCanteenId(String canteenId) {
        this.canteenId = canteenId == null ? null : canteenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_js_platform.address
     *
     * @return the value of dh_js_platform.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_js_platform.address
     *
     * @param address the value for dh_js_platform.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_js_platform.imageurl
     *
     * @return the value of dh_js_platform.imageurl
     *
     * @mbg.generated
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_js_platform.imageurl
     *
     * @param imageurl the value for dh_js_platform.imageurl
     *
     * @mbg.generated
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_js_platform.description
     *
     * @return the value of dh_js_platform.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_js_platform.description
     *
     * @param description the value for dh_js_platform.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_js_platform.is_delete
     *
     * @return the value of dh_js_platform.is_delete
     *
     * @mbg.generated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_js_platform.is_delete
     *
     * @param isDelete the value for dh_js_platform.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_js_platform.create_time
     *
     * @return the value of dh_js_platform.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_js_platform.create_time
     *
     * @param createTime the value for dh_js_platform.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_js_platform.create_user
     *
     * @return the value of dh_js_platform.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_js_platform.create_user
     *
     * @param createUser the value for dh_js_platform.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_js_platform.update_user
     *
     * @return the value of dh_js_platform.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_js_platform.update_user
     *
     * @param updateUser the value for dh_js_platform.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_js_platform.update_time
     *
     * @return the value of dh_js_platform.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_js_platform.update_time
     *
     * @param updateTime the value for dh_js_platform.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_js_platform.safetyone
     *
     * @return the value of dh_js_platform.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_js_platform.safetyone
     *
     * @param safetyone the value for dh_js_platform.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_js_platform.safetytwo
     *
     * @return the value of dh_js_platform.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_js_platform.safetytwo
     *
     * @param safetytwo the value for dh_js_platform.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }
}