package com.lswd.youpin.model.lsyp;

public class MealMenu {

    private String recipeIdBH;//菜品编号

    public String getRecipeIdBH() {
        return recipeIdBH;
    }

    public void setRecipeIdBH(String recipeIdBH) {
        this.recipeIdBH = recipeIdBH;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_mealmenu.meal_menu_id
     *
     * @mbg.generated
     */
    private Integer mealMenuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_mealmenu.meal_record_id
     *
     * @mbg.generated
     */
    private Integer mealRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_mealmenu.recipe_id
     *
     * @mbg.generated
     */
    private Integer recipeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_mealmenu.meal_menu_id
     *
     * @return the value of dh_mealmenu.meal_menu_id
     *
     * @mbg.generated
     */
    public Integer getMealMenuId() {
        return mealMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_mealmenu.meal_menu_id
     *
     * @param mealMenuId the value for dh_mealmenu.meal_menu_id
     *
     * @mbg.generated
     */
    public void setMealMenuId(Integer mealMenuId) {
        this.mealMenuId = mealMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_mealmenu.meal_record_id
     *
     * @return the value of dh_mealmenu.meal_record_id
     *
     * @mbg.generated
     */
    public Integer getMealRecordId() {
        return mealRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_mealmenu.meal_record_id
     *
     * @param mealRecordId the value for dh_mealmenu.meal_record_id
     *
     * @mbg.generated
     */
    public void setMealRecordId(Integer mealRecordId) {
        this.mealRecordId = mealRecordId;
    }

    public Integer getRecipeId() {
        return recipeId;
    }

    public void setRecipeId(Integer recipeId) {
        this.recipeId = recipeId;
    }
}