package com.lswd.youpin.model.lsyp;

import java.util.Date;

public class Rate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate.rate
     *
     * @mbg.generated
     */
    private Double rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate.canteen_id
     *
     * @mbg.generated
     */
    private String canteenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate.safetythree
     *
     * @mbg.generated
     */
    private String safetythree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate.id
     *
     * @return the value of t_rate.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate.id
     *
     * @param id the value for t_rate.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate.rate
     *
     * @return the value of t_rate.rate
     *
     * @mbg.generated
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate.rate
     *
     * @param rate the value for t_rate.rate
     *
     * @mbg.generated
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate.canteen_id
     *
     * @return the value of t_rate.canteen_id
     *
     * @mbg.generated
     */
    public String getCanteenId() {
        return canteenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate.canteen_id
     *
     * @param canteenId the value for t_rate.canteen_id
     *
     * @mbg.generated
     */
    public void setCanteenId(String canteenId) {
        this.canteenId = canteenId == null ? null : canteenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate.update_user
     *
     * @return the value of t_rate.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate.update_user
     *
     * @param updateUser the value for t_rate.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate.update_time
     *
     * @return the value of t_rate.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate.update_time
     *
     * @param updateTime the value for t_rate.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate.safetyone
     *
     * @return the value of t_rate.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate.safetyone
     *
     * @param safetyone the value for t_rate.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate.safetytwo
     *
     * @return the value of t_rate.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate.safetytwo
     *
     * @param safetytwo the value for t_rate.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate.safetythree
     *
     * @return the value of t_rate.safetythree
     *
     * @mbg.generated
     */
    public String getSafetythree() {
        return safetythree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate.safetythree
     *
     * @param safetythree the value for t_rate.safetythree
     *
     * @mbg.generated
     */
    public void setSafetythree(String safetythree) {
        this.safetythree = safetythree == null ? null : safetythree.trim();
    }
}