package com.lswd.youpin.model.lsyp;

import com.lswd.youpin.model.Canteen;

public class RecipeOrderItems {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_items_other.id
     *
     * @mbg.generated
     */
    private Integer id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_items_other.recipe_id
     *
     * @mbg.generated
     */
    private String recipeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_items_other.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_items_other.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_items_other.order_amount
     *
     * @mbg.generated
     */
    private Float orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_items_other.decription
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_items_other.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_items_other.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     *
     * @return
     */
    private Recipe recipe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_items_other.id
     *
     * @return the value of t_recipe_order_items_other.id
     *
     * @mbg.generated
     */

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_items_other.id
     *
     * @param id the value for t_recipe_order_items_other.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_items_other.recipe_id
     *
     * @return the value of t_recipe_order_items_other.recipe_id
     *
     * @mbg.generated
     */
    public String getRecipeId() {
        return recipeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_items_other.recipe_id
     *
     * @param recipeId the value for t_recipe_order_items_other.recipe_id
     *
     * @mbg.generated
     */
    public void setRecipeId(String recipeId) {
        this.recipeId = recipeId == null ? null : recipeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_items_other.quantity
     *
     * @return the value of t_recipe_order_items_other.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_items_other.quantity
     *
     * @param quantity the value for t_recipe_order_items_other.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_items_other.order_id
     *
     * @return the value of t_recipe_order_items_other.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_items_other.order_id
     *
     * @param orderId the value for t_recipe_order_items_other.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_items_other.order_amount
     *
     * @return the value of t_recipe_order_items_other.order_amount
     *
     * @mbg.generated
     */
    public Float getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_items_other.order_amount
     *
     * @param orderAmount the value for t_recipe_order_items_other.order_amount
     *
     * @mbg.generated
     */
    public void setOrderAmount(Float orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_items_other.description
     *
     * @return the value of t_recipe_order_items_other.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_items_other.description
     *
     * @param description the value for t_recipe_order_items_other.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {this.description = description == null ? null : description.trim();}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_items_other.safetyone
     *
     * @return the value of t_recipe_order_items_other.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_items_other.safetyone
     *
     * @param safetyone the value for t_recipe_order_items_other.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_items_other.safetytwo
     *
     * @return the value of t_recipe_order_items_other.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_items_other.safetytwo
     *
     * @param safetytwo the value for t_recipe_order_items_other.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }

    public Recipe getRecipe() {return recipe;}

    public void setRecipe(Recipe recipe) {this.recipe = recipe;}

    private String planId;

    public String getPlanId() {return planId;}

    public void setPlanId(String planId) {this.planId = planId==null?null:planId.trim();}

    private Canteen canteen;

    public Canteen getCanteen() {return canteen;}

    public void setCanteen(Canteen canteen) {this.canteen = canteen;}
}