package com.lswd.youpin.model.lsyp;

public class RecipeDetailsImg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_details_img.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_details_img.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_details_img.recipe_id
     *
     * @mbg.generated
     */
    private String recipeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_details_img.id
     *
     * @return the value of t_recipe_details_img.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_details_img.id
     *
     * @param id the value for t_recipe_details_img.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_details_img.img_url
     *
     * @return the value of t_recipe_details_img.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_details_img.img_url
     *
     * @param imgUrl the value for t_recipe_details_img.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_details_img.recipe_id
     *
     * @return the value of t_recipe_details_img.recipe_id
     *
     * @mbg.generated
     */
    public String getRecipeId() {
        return recipeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_details_img.recipe_id
     *
     * @param recipeId the value for t_recipe_details_img.recipe_id
     *
     * @mbg.generated
     */
    public void setRecipeId(String recipeId) {
        this.recipeId = recipeId == null ? null : recipeId.trim();
    }
}