package com.lswd.youpin.model.lsyp;

import java.util.Date;

public class RecipeSecKill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.recipe_id
     *
     * @mbg.generated
     */
    private String recipeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.recipe_name
     *
     * @mbg.generated
     */
    private String recipeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.canteen_id
     *
     * @mbg.generated
     */
    private String canteenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.recipe_type
     *
     * @mbg.generated
     */
    private Integer recipeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.dinner_time
     *
     * @mbg.generated
     */
    private Date dinnerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.sale_num
     *
     * @mbg.generated
     */
    private Integer saleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.imageurl
     *
     * @mbg.generated
     */
    private String imageurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.bigimageurl
     *
     * @mbg.generated
     */
    private String bigimageurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.guide_price
     *
     * @mbg.generated
     */
    private Float guidePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.market_price
     *
     * @mbg.generated
     */
    private Float marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_seckill.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.id
     *
     * @return the value of t_recipe_seckill.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.id
     *
     * @param id the value for t_recipe_seckill.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.recipe_id
     *
     * @return the value of t_recipe_seckill.recipe_id
     *
     * @mbg.generated
     */
    public String getRecipeId() {
        return recipeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.recipe_id
     *
     * @param recipeId the value for t_recipe_seckill.recipe_id
     *
     * @mbg.generated
     */
    public void setRecipeId(String recipeId) {
        this.recipeId = recipeId == null ? null : recipeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.recipe_name
     *
     * @return the value of t_recipe_seckill.recipe_name
     *
     * @mbg.generated
     */
    public String getRecipeName() {
        return recipeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.recipe_name
     *
     * @param recipeName the value for t_recipe_seckill.recipe_name
     *
     * @mbg.generated
     */
    public void setRecipeName(String recipeName) {
        this.recipeName = recipeName == null ? null : recipeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.canteen_id
     *
     * @return the value of t_recipe_seckill.canteen_id
     *
     * @mbg.generated
     */
    public String getCanteenId() {
        return canteenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.canteen_id
     *
     * @param canteenId the value for t_recipe_seckill.canteen_id
     *
     * @mbg.generated
     */
    public void setCanteenId(String canteenId) {
        this.canteenId = canteenId == null ? null : canteenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.recipe_type
     *
     * @return the value of t_recipe_seckill.recipe_type
     *
     * @mbg.generated
     */
    public Integer getRecipeType() {
        return recipeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.recipe_type
     *
     * @param recipeType the value for t_recipe_seckill.recipe_type
     *
     * @mbg.generated
     */
    public void setRecipeType(Integer recipeType) {
        this.recipeType = recipeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.dinner_time
     *
     * @return the value of t_recipe_seckill.dinner_time
     *
     * @mbg.generated
     */
    public Date getDinnerTime() {
        return dinnerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.dinner_time
     *
     * @param dinnerTime the value for t_recipe_seckill.dinner_time
     *
     * @mbg.generated
     */
    public void setDinnerTime(Date dinnerTime) {
        this.dinnerTime = dinnerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.sale_num
     *
     * @return the value of t_recipe_seckill.sale_num
     *
     * @mbg.generated
     */
    public Integer getSaleNum() {
        return saleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.sale_num
     *
     * @param saleNum the value for t_recipe_seckill.sale_num
     *
     * @mbg.generated
     */
    public void setSaleNum(Integer saleNum) {
        this.saleNum = saleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.imageurl
     *
     * @return the value of t_recipe_seckill.imageurl
     *
     * @mbg.generated
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.imageurl
     *
     * @param imageurl the value for t_recipe_seckill.imageurl
     *
     * @mbg.generated
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.bigimageurl
     *
     * @return the value of t_recipe_seckill.bigimageurl
     *
     * @mbg.generated
     */
    public String getBigimageurl() {
        return bigimageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.bigimageurl
     *
     * @param bigimageurl the value for t_recipe_seckill.bigimageurl
     *
     * @mbg.generated
     */
    public void setBigimageurl(String bigimageurl) {
        this.bigimageurl = bigimageurl == null ? null : bigimageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.guide_price
     *
     * @return the value of t_recipe_seckill.guide_price
     *
     * @mbg.generated
     */
    public Float getGuidePrice() {
        return guidePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.guide_price
     *
     * @param guidePrice the value for t_recipe_seckill.guide_price
     *
     * @mbg.generated
     */
    public void setGuidePrice(Float guidePrice) {
        this.guidePrice = guidePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.market_price
     *
     * @return the value of t_recipe_seckill.market_price
     *
     * @mbg.generated
     */
    public Float getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.market_price
     *
     * @param marketPrice the value for t_recipe_seckill.market_price
     *
     * @mbg.generated
     */
    public void setMarketPrice(Float marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.is_delete
     *
     * @return the value of t_recipe_seckill.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.is_delete
     *
     * @param isDelete the value for t_recipe_seckill.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.create_user
     *
     * @return the value of t_recipe_seckill.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.create_user
     *
     * @param createUser the value for t_recipe_seckill.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.update_user
     *
     * @return the value of t_recipe_seckill.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.update_user
     *
     * @param updateUser the value for t_recipe_seckill.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.create_time
     *
     * @return the value of t_recipe_seckill.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.create_time
     *
     * @param createTime the value for t_recipe_seckill.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.update_time
     *
     * @return the value of t_recipe_seckill.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.update_time
     *
     * @param updateTime the value for t_recipe_seckill.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.safetyone
     *
     * @return the value of t_recipe_seckill.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.safetyone
     *
     * @param safetyone the value for t_recipe_seckill.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_seckill.safetytwo
     *
     * @return the value of t_recipe_seckill.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_seckill.safetytwo
     *
     * @param safetytwo the value for t_recipe_seckill.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }
}