package com.lswd.youpin.model.lsyp;

public class RecipePlanItems {

    private boolean isHot = false;//是否热销
    private float priceDay;//当天售卖价格
    private float marketPriceDay;//当天市场价格、
    private Integer surplus;//库存,默认未99
    private Boolean isDelete  = false;
    private Recipe recipe;
    private Short recipeType;//早、午、晚

    public boolean isHot() {
        return isHot;
    }

    public void setHot(boolean hot) {
        isHot = hot;
    }

    public float getPriceDay() {
        return priceDay;
    }

    public void setPriceDay(float priceDay) {
        this.priceDay = priceDay;
    }

    public float getMarketPriceDay() {
        return marketPriceDay;
    }

    public void setMarketPriceDay(float marketPriceDay) {
        this.marketPriceDay = marketPriceDay;
    }

    public Boolean getDelete() {
        return isDelete;
    }

    public void setDelete(Boolean delete) {
        isDelete = delete;
    }

    public Integer getSurplus() {
        return surplus;
    }

    public void setSurplus(Integer surplus) {
        this.surplus = surplus;
    }

    public Recipe getRecipe() {
        return recipe;
    }

    public void setRecipe(Recipe recipe) {
        this.recipe = recipe;
    }

    public Short getRecipeType() {
        return recipeType;
    }

    public void setRecipeType(Short recipeType) {
        this.recipeType = recipeType;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_planitems.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_planitems.recipe_id
     *
     * @mbg.generated
     */
    private String recipeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_planitems.recipe_plan_id
     *
     * @mbg.generated
     */
    private String recipePlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_planitems.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_planitems.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_planitems.id
     *
     * @return the value of t_recipe_planitems.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_planitems.id
     *
     * @param id the value for t_recipe_planitems.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_planitems.recipe_id
     *
     * @return the value of t_recipe_planitems.recipe_id
     *
     * @mbg.generated
     */
    public String getRecipeId() {
        return recipeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_planitems.recipe_id
     *
     * @param recipeId the value for t_recipe_planitems.recipe_id
     *
     * @mbg.generated
     */
    public void setRecipeId(String recipeId) {
        this.recipeId = recipeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_planitems.recipe_plan_id
     *
     * @return the value of t_recipe_planitems.recipe_plan_id
     *
     * @mbg.generated
     */
    public String getRecipePlanId() {
        return recipePlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_planitems.recipe_plan_id
     *
     * @param recipePlanId the value for t_recipe_planitems.recipe_plan_id
     *
     * @mbg.generated
     */
    public void setRecipePlanId(String recipePlanId) {
        this.recipePlanId = recipePlanId == null ? null : recipePlanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_planitems.safetyone
     *
     * @return the value of t_recipe_planitems.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_planitems.safetyone
     *
     * @param safetyone the value for t_recipe_planitems.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_planitems.safetytwo
     *
     * @return the value of t_recipe_planitems.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_planitems.safetytwo
     *
     * @param safetytwo the value for t_recipe_planitems.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }
}