package com.lswd.youpin.model.lsyp;

import java.util.Date;

public class RecipeOther {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_other_paid.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_other_paid.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_other_paid.associator_id
     *
     * @mbg.generated
     */
    private String associatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_other_paid.eat_time
     *
     * @mbg.generated
     */
    private Date eatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_other_paid.order_amount
     *
     * @mbg.generated
     */
    private Float orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_other_paid.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_other_paid.pay_type
     *
     * @mbg.generated
     */
    private Short payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_other_paid.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_other_paid.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_other_paid.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_other_paid.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_other_paid.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recipe_order_other_paid.safetythree
     *
     * @mbg.generated
     */
    private String safetythree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_other_paid.id
     *
     * @return the value of t_recipe_order_other_paid.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_other_paid.id
     *
     * @param id the value for t_recipe_order_other_paid.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_other_paid.order_id
     *
     * @return the value of t_recipe_order_other_paid.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_other_paid.order_id
     *
     * @param orderId the value for t_recipe_order_other_paid.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_other_paid.associator_id
     *
     * @return the value of t_recipe_order_other_paid.associator_id
     *
     * @mbg.generated
     */
    public String getAssociatorId() {
        return associatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_other_paid.associator_id
     *
     * @param associatorId the value for t_recipe_order_other_paid.associator_id
     *
     * @mbg.generated
     */
    public void setAssociatorId(String associatorId) {
        this.associatorId = associatorId == null ? null : associatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_other_paid.eat_time
     *
     * @return the value of t_recipe_order_other_paid.eat_time
     *
     * @mbg.generated
     */
    public Date getEatTime() {
        return eatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_other_paid.eat_time
     *
     * @param eatTime the value for t_recipe_order_other_paid.eat_time
     *
     * @mbg.generated
     */
    public void setEatTime(Date eatTime) {
        this.eatTime = eatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_other_paid.order_amount
     *
     * @return the value of t_recipe_order_other_paid.order_amount
     *
     * @mbg.generated
     */
    public Float getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_other_paid.order_amount
     *
     * @param orderAmount the value for t_recipe_order_other_paid.order_amount
     *
     * @mbg.generated
     */
    public void setOrderAmount(Float orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_other_paid.status
     *
     * @return the value of t_recipe_order_other_paid.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_other_paid.status
     *
     * @param status the value for t_recipe_order_other_paid.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_other_paid.pay_type
     *
     * @return the value of t_recipe_order_other_paid.pay_type
     *
     * @mbg.generated
     */
    public Short getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_other_paid.pay_type
     *
     * @param payType the value for t_recipe_order_other_paid.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(Short payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_other_paid.description
     *
     * @return the value of t_recipe_order_other_paid.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_other_paid.description
     *
     * @param description the value for t_recipe_order_other_paid.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_other_paid.create_time
     *
     * @return the value of t_recipe_order_other_paid.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_other_paid.create_time
     *
     * @param createTime the value for t_recipe_order_other_paid.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_other_paid.update_time
     *
     * @return the value of t_recipe_order_other_paid.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_other_paid.update_time
     *
     * @param updateTime the value for t_recipe_order_other_paid.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_other_paid.safetyone
     *
     * @return the value of t_recipe_order_other_paid.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_other_paid.safetyone
     *
     * @param safetyone the value for t_recipe_order_other_paid.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_other_paid.safetytwo
     *
     * @return the value of t_recipe_order_other_paid.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_other_paid.safetytwo
     *
     * @param safetytwo the value for t_recipe_order_other_paid.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recipe_order_other_paid.safetythree
     *
     * @return the value of t_recipe_order_other_paid.safetythree
     *
     * @mbg.generated
     */
    public String getSafetythree() {
        return safetythree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recipe_order_other_paid.safetythree
     *
     * @param safetythree the value for t_recipe_order_other_paid.safetythree
     *
     * @mbg.generated
     */
    public void setSafetythree(String safetythree) {
        this.safetythree = safetythree == null ? null : safetythree.trim();
    }
}