package com.lswd.youpin.dao.lsypgen;

import com.lswd.youpin.model.lsyp.CartItems;

public interface CartItemsMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cartitems
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cartitems
     *
     * @mbg.generated
     */
    int insert(CartItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cartitems
     *
     * @mbg.generated
     */
    int insertSelective(CartItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cartitems
     *
     * @mbg.generated
     */
    CartItems selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cartitems
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CartItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cartitems
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CartItems record);
}