package com.lswd.youpin.dao.lsypgen;

import com.lswd.youpin.model.lsyp.CounterMenu;

public interface CounterMenuMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_counter_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_counter_menu
     *
     * @mbg.generated
     */
    int insert(CounterMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_counter_menu
     *
     * @mbg.generated
     */
    int insertSelective(CounterMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_counter_menu
     *
     * @mbg.generated
     */
    CounterMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_counter_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CounterMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_counter_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CounterMenu record);
}