package com.lswd.youpin.dao.lsypgen;

import com.lswd.youpin.model.lsyp.CounterTypeRecipeCategory;

public interface CounterTypeRecipeCategoryMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_counter_type_recipe_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_counter_type_recipe_category
     *
     * @mbg.generated
     */
    int insert(CounterTypeRecipeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_counter_type_recipe_category
     *
     * @mbg.generated
     */
    int insertSelective(CounterTypeRecipeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_counter_type_recipe_category
     *
     * @mbg.generated
     */
    CounterTypeRecipeCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_counter_type_recipe_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CounterTypeRecipeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_counter_type_recipe_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CounterTypeRecipeCategory record);
}