package com.lswd.youpin.dao.lsypgen;

import com.lswd.youpin.model.lsyp.DiskRecipe;

public interface DiskRecipeMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_disk_recipe
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_disk_recipe
     *
     * @mbg.generated
     */
    int insert(DiskRecipe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_disk_recipe
     *
     * @mbg.generated
     */
    int insertSelective(DiskRecipe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_disk_recipe
     *
     * @mbg.generated
     */
    DiskRecipe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_disk_recipe
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DiskRecipe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_disk_recipe
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DiskRecipe record);
}