package com.lswd.youpin.dao.lsypgen;

import com.lswd.youpin.model.lsyp.Good;

public interface GoodMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    int insert(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    int insertSelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    Good selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Good record);
}