package com.lswd.youpin.dao.lsypgen;

import com.lswd.youpin.model.lsyp.GoodDetailsImg;

public interface GoodDetailsImgMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good_details_img
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good_details_img
     *
     * @mbg.generated
     */
    int insert(GoodDetailsImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good_details_img
     *
     * @mbg.generated
     */
    int insertSelective(GoodDetailsImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good_details_img
     *
     * @mbg.generated
     */
    GoodDetailsImg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good_details_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodDetailsImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good_details_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodDetailsImg record);
}