package com.lswd.youpin.dao.lsypgen;

import com.lswd.youpin.model.lsyp.JSPlatform;

public interface JSPlatformMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_js_platform
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_js_platform
     *
     * @mbg.generated
     */
    int insert(JSPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_js_platform
     *
     * @mbg.generated
     */
    int insertSelective(JSPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_js_platform
     *
     * @mbg.generated
     */
    JSPlatform selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_js_platform
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JSPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_js_platform
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JSPlatform record);
}