package com.lswd.youpin.dao.lsypgen;

import com.lswd.youpin.model.lsyp.Label;

public interface LabelMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_disk_label
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_disk_label
     *
     * @mbg.generated
     */
    int insert(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_disk_label
     *
     * @mbg.generated
     */
    int insertSelective(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_disk_label
     *
     * @mbg.generated
     */
    Label selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_disk_label
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_disk_label
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Label record);
}