package com.lswd.youpin.dao.lsypgen;

import com.lswd.youpin.model.lsyp.MealMenu;

public interface MealMenuMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_mealmenu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mealMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_mealmenu
     *
     * @mbg.generated
     */
    int insert(MealMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_mealmenu
     *
     * @mbg.generated
     */
    int insertSelective(MealMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_mealmenu
     *
     * @mbg.generated
     */
    MealMenu selectByPrimaryKey(Integer mealMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_mealmenu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MealMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_mealmenu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MealMenu record);
}