package com.lswd.youpin.dao.lsypgen;

import com.lswd.youpin.model.lsyp.MemberType;

public interface MemberTypeMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_member_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_member_type
     *
     * @mbg.generated
     */
    int insert(MemberType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_member_type
     *
     * @mbg.generated
     */
    int insertSelective(MemberType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_member_type
     *
     * @mbg.generated
     */
    MemberType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_member_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MemberType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_member_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberType record);
}