package com.lswd.youpin.dao.lsypgen;

import com.lswd.youpin.model.lsyp.MenuType;

public interface MenuTypeMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_menutype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_menutype
     *
     * @mbg.generated
     */
    int insert(MenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_menutype
     *
     * @mbg.generated
     */
    int insertSelective(MenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_menutype
     *
     * @mbg.generated
     */
    MenuType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_menutype
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_menutype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MenuType record);
}