package com.lswd.youpin.dao.lsypgen;

import com.lswd.youpin.model.lsyp.RecipeDetailsImg;

public interface RecipeDetailsImgMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_details_img
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_details_img
     *
     * @mbg.generated
     */
    int insert(RecipeDetailsImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_details_img
     *
     * @mbg.generated
     */
    int insertSelective(RecipeDetailsImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_details_img
     *
     * @mbg.generated
     */
    RecipeDetailsImg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_details_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RecipeDetailsImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_details_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RecipeDetailsImg record);
}