package com.lswd.youpin.dao.lsypgen;

import com.lswd.youpin.model.lsyp.RecipeComment;

public interface RecipeCommentMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_comment
     *
     * @mbg.generated
     */
    int insert(RecipeComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_comment
     *
     * @mbg.generated
     */
    int insertSelective(RecipeComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_comment
     *
     * @mbg.generated
     */
    RecipeComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RecipeComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RecipeComment record);
}