package com.lswd.youpin.dao.lsypgen;

import com.lswd.youpin.model.lsyp.RecipeOrderItems;

public interface RecipeOrderItemsMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_order_items_other
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_order_items_other
     *
     * @mbg.generated
     */
    int insert(RecipeOrderItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_order_items_other
     *
     * @mbg.generated
     */
    int insertSelective(RecipeOrderItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_order_items_other
     *
     * @mbg.generated
     */
    RecipeOrderItems selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_order_items_other
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RecipeOrderItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_order_items_other
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RecipeOrderItems record);
}