package com.lswd.youpin.dao.lsypgen;

import com.lswd.youpin.model.lsyp.RecipePlan;

public interface RecipePlanMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_plan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_plan
     *
     * @mbg.generated
     */
    int insert(RecipePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_plan
     *
     * @mbg.generated
     */
    int insertSelective(RecipePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_plan
     *
     * @mbg.generated
     */
    RecipePlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RecipePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipe_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RecipePlan record);
}