package com.lswd.youpin.model.lsy;

public class AppResourceMachine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_app_resource_machine.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_app_resource_machine.resouce_id
     *
     * @mbg.generated
     */
    private Integer resouceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_app_resource_machine.machine_id
     *
     * @mbg.generated
     */
    private Integer machineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_app_resource_machine.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_app_resource_machine.id
     *
     * @return the value of y_app_resource_machine.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_app_resource_machine.id
     *
     * @param id the value for y_app_resource_machine.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_app_resource_machine.resouce_id
     *
     * @return the value of y_app_resource_machine.resouce_id
     *
     * @mbg.generated
     */
    public Integer getResouceId() {
        return resouceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_app_resource_machine.resouce_id
     *
     * @param resouceId the value for y_app_resource_machine.resouce_id
     *
     * @mbg.generated
     */
    public void setResouceId(Integer resouceId) {
        this.resouceId = resouceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_app_resource_machine.machine_id
     *
     * @return the value of y_app_resource_machine.machine_id
     *
     * @mbg.generated
     */
    public Integer getMachineId() {
        return machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_app_resource_machine.machine_id
     *
     * @param machineId the value for y_app_resource_machine.machine_id
     *
     * @mbg.generated
     */
    public void setMachineId(Integer machineId) {
        this.machineId = machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_app_resource_machine.safetyone
     *
     * @return the value of y_app_resource_machine.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_app_resource_machine.safetyone
     *
     * @param safetyone the value for y_app_resource_machine.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }
}