package com.lswd.youpin.model.lsy;

import java.util.Date;

public class Banner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_banner.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_banner.banner_title
     *
     * @mbg.generated
     */
    private String bannerTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_banner.small_banner_url
     *
     * @mbg.generated
     */
    private String smallBannerUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_banner.banner_url
     *
     * @mbg.generated
     */
    private String bannerUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_banner.page_id
     *
     * @mbg.generated
     */
    private Integer pageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_banner.machine_id
     *
     * @mbg.generated
     */
    private Integer machineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_banner.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_banner.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_banner.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_banner.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_banner.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_banner.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_banner.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_banner.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_banner.safetythree
     *
     * @mbg.generated
     */
    private String safetythree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_banner.id
     *
     * @return the value of y_banner.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_banner.id
     *
     * @param id the value for y_banner.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_banner.banner_title
     *
     * @return the value of y_banner.banner_title
     *
     * @mbg.generated
     */
    public String getBannerTitle() {
        return bannerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_banner.banner_title
     *
     * @param bannerTitle the value for y_banner.banner_title
     *
     * @mbg.generated
     */
    public void setBannerTitle(String bannerTitle) {
        this.bannerTitle = bannerTitle == null ? null : bannerTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_banner.small_banner_url
     *
     * @return the value of y_banner.small_banner_url
     *
     * @mbg.generated
     */
    public String getSmallBannerUrl() {
        return smallBannerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_banner.small_banner_url
     *
     * @param smallBannerUrl the value for y_banner.small_banner_url
     *
     * @mbg.generated
     */
    public void setSmallBannerUrl(String smallBannerUrl) {
        this.smallBannerUrl = smallBannerUrl == null ? null : smallBannerUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_banner.banner_url
     *
     * @return the value of y_banner.banner_url
     *
     * @mbg.generated
     */
    public String getBannerUrl() {
        return bannerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_banner.banner_url
     *
     * @param bannerUrl the value for y_banner.banner_url
     *
     * @mbg.generated
     */
    public void setBannerUrl(String bannerUrl) {
        this.bannerUrl = bannerUrl == null ? null : bannerUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_banner.page_id
     *
     * @return the value of y_banner.page_id
     *
     * @mbg.generated
     */
    public Integer getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_banner.page_id
     *
     * @param pageId the value for y_banner.page_id
     *
     * @mbg.generated
     */
    public void setPageId(Integer pageId) {
        this.pageId = pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_banner.machine_id
     *
     * @return the value of y_banner.machine_id
     *
     * @mbg.generated
     */
    public Integer getMachineId() {
        return machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_banner.machine_id
     *
     * @param machineId the value for y_banner.machine_id
     *
     * @mbg.generated
     */
    public void setMachineId(Integer machineId) {
        this.machineId = machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_banner.is_delete
     *
     * @return the value of y_banner.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_banner.is_delete
     *
     * @param isDelete the value for y_banner.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_banner.description
     *
     * @return the value of y_banner.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_banner.description
     *
     * @param description the value for y_banner.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_banner.create_user
     *
     * @return the value of y_banner.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_banner.create_user
     *
     * @param createUser the value for y_banner.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_banner.create_time
     *
     * @return the value of y_banner.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_banner.create_time
     *
     * @param createTime the value for y_banner.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_banner.update_user
     *
     * @return the value of y_banner.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_banner.update_user
     *
     * @param updateUser the value for y_banner.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_banner.update_time
     *
     * @return the value of y_banner.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_banner.update_time
     *
     * @param updateTime the value for y_banner.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_banner.safetyone
     *
     * @return the value of y_banner.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_banner.safetyone
     *
     * @param safetyone the value for y_banner.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_banner.safetytwo
     *
     * @return the value of y_banner.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_banner.safetytwo
     *
     * @param safetytwo the value for y_banner.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_banner.safetythree
     *
     * @return the value of y_banner.safetythree
     *
     * @mbg.generated
     */
    public String getSafetythree() {
        return safetythree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_banner.safetythree
     *
     * @param safetythree the value for y_banner.safetythree
     *
     * @mbg.generated
     */
    public void setSafetythree(String safetythree) {
        this.safetythree = safetythree == null ? null : safetythree.trim();
    }
}