package com.lswd.youpin.model.lsy;

import java.util.Date;

public class Video {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.video_name
     *
     * @mbg.generated
     */
    private String videoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.video_url
     *
     * @mbg.generated
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.page_id
     *
     * @mbg.generated
     */
    private Integer pageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.video_time
     *
     * @mbg.generated
     */
    private Integer videoTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.video_size
     *
     * @mbg.generated
     */
    private Integer videoSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.video_extension
     *
     * @mbg.generated
     */
    private String videoExtension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.is_use
     *
     * @mbg.generated
     */
    private Boolean isUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.sequence
     *
     * @mbg.generated
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.machine_id
     *
     * @mbg.generated
     */
    private Integer machineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.safetyone
     *
     * @mbg.generated
     */
    private String safetyone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.safetytwo
     *
     * @mbg.generated
     */
    private String safetytwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_video.safetythree
     *
     * @mbg.generated
     */
    private String safetythree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.id
     *
     * @return the value of y_video.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.id
     *
     * @param id the value for y_video.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.video_name
     *
     * @return the value of y_video.video_name
     *
     * @mbg.generated
     */
    public String getVideoName() {
        return videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.video_name
     *
     * @param videoName the value for y_video.video_name
     *
     * @mbg.generated
     */
    public void setVideoName(String videoName) {
        this.videoName = videoName == null ? null : videoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.video_url
     *
     * @return the value of y_video.video_url
     *
     * @mbg.generated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.video_url
     *
     * @param videoUrl the value for y_video.video_url
     *
     * @mbg.generated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.page_id
     *
     * @return the value of y_video.page_id
     *
     * @mbg.generated
     */
    public Integer getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.page_id
     *
     * @param pageId the value for y_video.page_id
     *
     * @mbg.generated
     */
    public void setPageId(Integer pageId) {
        this.pageId = pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.video_time
     *
     * @return the value of y_video.video_time
     *
     * @mbg.generated
     */
    public Integer getVideoTime() {
        return videoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.video_time
     *
     * @param videoTime the value for y_video.video_time
     *
     * @mbg.generated
     */
    public void setVideoTime(Integer videoTime) {
        this.videoTime = videoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.video_size
     *
     * @return the value of y_video.video_size
     *
     * @mbg.generated
     */
    public Integer getVideoSize() {
        return videoSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.video_size
     *
     * @param videoSize the value for y_video.video_size
     *
     * @mbg.generated
     */
    public void setVideoSize(Integer videoSize) {
        this.videoSize = videoSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.video_extension
     *
     * @return the value of y_video.video_extension
     *
     * @mbg.generated
     */
    public String getVideoExtension() {
        return videoExtension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.video_extension
     *
     * @param videoExtension the value for y_video.video_extension
     *
     * @mbg.generated
     */
    public void setVideoExtension(String videoExtension) {
        this.videoExtension = videoExtension == null ? null : videoExtension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.is_use
     *
     * @return the value of y_video.is_use
     *
     * @mbg.generated
     */
    public Boolean getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.is_use
     *
     * @param isUse the value for y_video.is_use
     *
     * @mbg.generated
     */
    public void setIsUse(Boolean isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.img_url
     *
     * @return the value of y_video.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.img_url
     *
     * @param imgUrl the value for y_video.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.sequence
     *
     * @return the value of y_video.sequence
     *
     * @mbg.generated
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.sequence
     *
     * @param sequence the value for y_video.sequence
     *
     * @mbg.generated
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.is_delete
     *
     * @return the value of y_video.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.is_delete
     *
     * @param isDelete the value for y_video.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.machine_id
     *
     * @return the value of y_video.machine_id
     *
     * @mbg.generated
     */
    public Integer getMachineId() {
        return machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.machine_id
     *
     * @param machineId the value for y_video.machine_id
     *
     * @mbg.generated
     */
    public void setMachineId(Integer machineId) {
        this.machineId = machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.create_user
     *
     * @return the value of y_video.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.create_user
     *
     * @param createUser the value for y_video.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.create_time
     *
     * @return the value of y_video.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.create_time
     *
     * @param createTime the value for y_video.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.update_user
     *
     * @return the value of y_video.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.update_user
     *
     * @param updateUser the value for y_video.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.update_time
     *
     * @return the value of y_video.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.update_time
     *
     * @param updateTime the value for y_video.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.safetyone
     *
     * @return the value of y_video.safetyone
     *
     * @mbg.generated
     */
    public String getSafetyone() {
        return safetyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.safetyone
     *
     * @param safetyone the value for y_video.safetyone
     *
     * @mbg.generated
     */
    public void setSafetyone(String safetyone) {
        this.safetyone = safetyone == null ? null : safetyone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.safetytwo
     *
     * @return the value of y_video.safetytwo
     *
     * @mbg.generated
     */
    public String getSafetytwo() {
        return safetytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.safetytwo
     *
     * @param safetytwo the value for y_video.safetytwo
     *
     * @mbg.generated
     */
    public void setSafetytwo(String safetytwo) {
        this.safetytwo = safetytwo == null ? null : safetytwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_video.safetythree
     *
     * @return the value of y_video.safetythree
     *
     * @mbg.generated
     */
    public String getSafetythree() {
        return safetythree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_video.safetythree
     *
     * @param safetythree the value for y_video.safetythree
     *
     * @mbg.generated
     */
    public void setSafetythree(String safetythree) {
        this.safetythree = safetythree == null ? null : safetythree.trim();
    }
}