package com.lswd.youpin.daogen;

import com.lswd.youpin.model.AssociatorCanteen;

public interface AssociatorCanteenMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_associator_canteen
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_associator_canteen
     *
     * @mbg.generated
     */
    int insert(AssociatorCanteen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_associator_canteen
     *
     * @mbg.generated
     */
    int insertSelective(AssociatorCanteen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_associator_canteen
     *
     * @mbg.generated
     */
    AssociatorCanteen selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_associator_canteen
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AssociatorCanteen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_associator_canteen
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AssociatorCanteen record);
}