package com.lswd.youpin.daogen;

import com.lswd.youpin.model.AssociatorCard;

public interface AssociatorCardMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_card
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_card
     *
     * @mbg.generated
     */
    int insert(AssociatorCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_card
     *
     * @mbg.generated
     */
    int insertSelective(AssociatorCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_card
     *
     * @mbg.generated
     */
    AssociatorCard selectByPrimaryKey(Integer cardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AssociatorCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AssociatorCard record);
}