package com.lswd.youpin.daogen;

import com.lswd.youpin.model.AssociatorPayBill;

public interface AssociatorPayBillMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_associator_paybill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_associator_paybill
     *
     * @mbg.generated
     */
    int insert(AssociatorPayBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_associator_paybill
     *
     * @mbg.generated
     */
    int insertSelective(AssociatorPayBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_associator_paybill
     *
     * @mbg.generated
     */
    AssociatorPayBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_associator_paybill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AssociatorPayBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_associator_paybill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AssociatorPayBill record);
}