package com.lswd.youpin.daogen;

import com.lswd.youpin.model.CounterUser;

public interface CounterUserMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_count_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_count_user
     *
     * @mbg.generated
     */
    int insert(CounterUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_count_user
     *
     * @mbg.generated
     */
    int insertSelective(CounterUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_count_user
     *
     * @mbg.generated
     */
    CounterUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_count_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CounterUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_count_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CounterUser record);
}