package com.lswd.youpin.daogen;

import com.lswd.youpin.model.RechargeLog;

public interface RechargeLogMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_log
     *
     * @mbg.generated
     */
    int insert(RechargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_log
     *
     * @mbg.generated
     */
    int insertSelective(RechargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_log
     *
     * @mbg.generated
     */
    RechargeLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RechargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RechargeLog record);
}