package com.lswd.youpin.daogen;

import com.lswd.youpin.model.TenantAssociator;

public interface TenantAssociatorMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tenant_associator
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tenant_associator
     *
     * @mbg.generated
     */
    int insert(TenantAssociator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tenant_associator
     *
     * @mbg.generated
     */
    int insertSelective(TenantAssociator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tenant_associator
     *
     * @mbg.generated
     */
    TenantAssociator selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tenant_associator
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TenantAssociator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tenant_associator
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TenantAssociator record);
}