package com.lswd.youpin.daogen;

import com.lswd.youpin.model.UserLog;

public interface UserLogMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbg.generated
     */
    int insert(UserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbg.generated
     */
    int insertSelective(UserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbg.generated
     */
    UserLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(UserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserLog record);
}